export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  categoryName: string;
  subCategory?: string;
  price: number;
  originalPrice: number;
  discountPercent: number;
  inStock: boolean;
  stockCount: number;
  rating: number;
  reviewCount: number;
  image: string;
  gallery?: string[];
  description: string;
  specs: Record<string, string>;
  features: string[];
  isFeatured?: boolean;
}

export interface StoreCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  itemCount: number;
  color: string;
  subCategories: string[];
}

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    id: 'microcontrollers',
    name: 'Microcontrollers',
    slug: 'microcontrollers',
    description: 'High-performance ESP32, ESP8266, and Arduino microcontroller development boards and modules.',
    icon: 'Cpu',
    itemCount: 7,
    color: 'from-[#0066FF] to-[#2563EB]',
    subCategories: ['ESP32 Series', 'Arduino Boards']
  },
  {
    id: 'sensors',
    name: 'Sensors',
    slug: 'sensors',
    description: 'Precision environmental, motion, optical, biometric, gas, and distance sensing modules.',
    icon: 'Wifi',
    itemCount: 10,
    color: 'from-[#0066FF] to-[#0284C7]',
    subCategories: ['Environmental & Gas', 'Motion & Proximity', 'Optical & Sound', 'Biometric']
  },
  {
    id: 'modules',
    name: 'Modules',
    slug: 'modules',
    description: 'Relay drivers, charger controllers, audio amplifiers, wireless transceivers, and RTC modules.',
    icon: 'Layers',
    itemCount: 10,
    color: 'from-blue-600 to-indigo-700',
    subCategories: ['Relays & Drivers', 'Charging & Power', 'Audio & Wireless', 'Timing & Interfaces']
  },
  {
    id: 'displays',
    name: 'Displays',
    slug: 'displays',
    description: 'High-resolution OLED screens, TFT LCD touch displays, 16x2 LCDs, and WS2812B addressable LEDs.',
    icon: 'Monitor',
    itemCount: 13,
    color: 'from-cyan-600 to-blue-700',
    subCategories: ['OLED Displays', 'TFT Displays', 'LCD & Matrix', 'LED Lighting']
  },
  {
    id: 'motors-drivers',
    name: 'Motors & Drivers',
    slug: 'motors-drivers',
    description: 'Precision servos, stepper motors, DC gear motors, motor driver ICs, and robot chassis components.',
    icon: 'Cog',
    itemCount: 17,
    color: 'from-slate-700 to-slate-900',
    subCategories: ['Servo Motors', 'Stepper Motors', 'DC Motors', 'Motor Drivers & Chassis']
  },
  {
    id: 'power-battery',
    name: 'Power & Battery',
    slug: 'power-battery',
    description: 'Li-Ion 18650 cells, Li-Po batteries, BMS protection boards, buck/boost converters, and power connectors.',
    icon: 'BatteryCharging',
    itemCount: 22,
    color: 'from-emerald-600 to-teal-700',
    subCategories: ['Li-Ion & Li-Po', 'BMS & Chargers', 'Voltage Regulators & Holders', 'Connectors & Switches']
  }
];

export const STORE_PRODUCTS: Product[] = [
  // 1. ESP32-WROOM-32
  {
    id: 'mc-1',
    name: 'ESP32-WROOM-32',
    slug: 'esp32-wroom-32',
    sku: 'SKU-MC-01',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248395/awie_store/microcontrollers/esp32-wroom-32-module/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248395/awie_store/microcontrollers/esp32-wroom-32-module/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248396/awie_store/microcontrollers/esp32-wroom-32-module/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248394/awie_store/microcontrollers/esp32-wroom-32-module/gpio-view.jpg'
    ],
    description: 'ESP32-WROOM-32 is a powerful, general-purpose Wi-Fi + Bluetooth + BLE MCU module by Espressif. Powered by the ESP32-D0WDQ6 dual-core 32-bit Tensilica Xtensa LX6 processor operating at up to 240 MHz, it integrates 4 MB SPI flash, an onboard PCB antenna, and rich peripheral interfaces. Note: Espressif marks original ESP32-WROOM-32 as NRND (Not Recommended for New Designs); recommended for existing production or replacement needs.',
    features: [
      'Dual-core 32-bit Tensilica Xtensa LX6 processor @ up to 240 MHz',
      '448 KB ROM, 520 KB SRAM, 4 MB integrated SPI Flash',
      '802.11 b/g/n Wi-Fi (2.4 GHz, up to 150 Mbps)',
      'Bluetooth v4.2 BR/EDR & BLE (Bluetooth Low Energy)',
      'Up to 32 configurable GPIO pins',
      'Rich peripherals: 12-bit ADC (18 ch), 2x 8-bit DAC, 3x UART, 3x SPI, 2x I2C, 2x I2S, 16x PWM, TWAI (CAN 2.0)',
      '10x Capacitive Touch sensor channels',
      'Operating Voltage: 3.0 V – 3.6 V (3.3 V Typical)',
      'Ultra-compact module dimensions: 18.00 × 25.50 × 3.10 mm',
      'Integrated PCB trace antenna'
    ],
    specs: {
      'MCU Core': 'ESP32-D0WDQ6 (Dual-Core Xtensa LX6)',
      'Clock Speed': '80 MHz to 240 MHz',
      'Internal SRAM': '520 KB',
      'ROM': '448 KB',
      'Flash Memory': '4 MB SPI Flash',
      'Wi-Fi Standard': '802.11 b/g/n (2.4 GHz)',
      'Bluetooth': 'v4.2 BR/EDR & BLE',
      'GPIO Count': 'Up to 32 Pins',
      'Analog Peripherals': '12-bit ADC (18 Channels), 2x 8-bit DAC',
      'Digital Interfaces': '3x UART, 3x SPI, 2x I2C, 2x I2S, 16x PWM, TWAI (CAN 2.0)',
      'Touch Sensing': '10 Capacitive Touch Pins',
      'Operating Voltage': '3.0 V – 3.6 V (3.3 V Nom.)',
      'Operating Current': '80 mA Average (Deep Sleep < 10 µA)',
      'Module Dimensions': '18.00 × 25.50 × 3.10 mm',
      'Lifecycle Status': 'NRND (Espressif Official)'
    },
    isFeatured: true
  },

  // 2. ESP32-C3 SuperMini
  {
    id: 'mc-3',
    name: 'ESP32-C3 SuperMini',
    slug: 'esp32-c3-supermini',
    sku: 'SKU-MC-03',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248398/awie_store/microcontrollers/esp32-c3-supermini/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248398/awie_store/microcontrollers/esp32-c3-supermini/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248399/awie_store/microcontrollers/esp32-c3-supermini/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248397/awie_store/microcontrollers/esp32-c3-supermini/gpio-view.jpg'
    ],
    description: 'ESP32-C3 SuperMini is an ultra-compact RISC-V 32-bit single-core development board equipped with native USB Type-C, Wi-Fi 4, and Bluetooth 5.0 LE. Operating at up to 160 MHz, its miniature 22.5 × 18 mm footprint with castellated holes makes it ideal for space-constrained wearables and smart IoT nodes.',
    features: [
      '32-bit RISC-V single-core processor up to 160 MHz',
      '400 KB SRAM, 384 KB ROM, 4 MB integrated SPI Flash',
      '2.4 GHz Wi-Fi 802.11 b/g/n & Bluetooth 5 (LE) / Mesh support',
      'Native USB Type-C interface for CDC/JTAG debugging and power',
      '11x Digital GPIOs, 4x ADC channels, 1x SPI, 1x I2C, 1x UART, PWM on all pins',
      'Castellated holes for SMD surface mounting or pin header usage',
      'Ultra-compact form factor (22.5 × 18.0 mm)'
    ],
    specs: {
      'MCU Architecture': '32-bit RISC-V Single-Core (ESP32-C3)',
      'Clock Speed': 'Up to 160 MHz',
      'SRAM / ROM': '400 KB SRAM / 384 KB ROM',
      'Flash Memory': '4 MB SPI Flash',
      'Wi-Fi': '2.4 GHz 802.11 b/g/n (150 Mbps)',
      'Bluetooth': 'Bluetooth 5.0 LE & Mesh',
      'USB Port': 'Native USB Type-C (Serial / JTAG)',
      'GPIO Count': '11 Digital GPIOs',
      'Analog Inputs': '4-Channel 12-bit ADC',
      'Operating Voltage': '3.3 V Logic (5 V Input via USB/VIN)',
      'Dimensions': '22.5 × 18.0 × 4.5 mm'
    }
  },

  // 5. ESP32-S3 DevKit
  {
    id: 'mc-5',
    name: 'ESP32-S3 DevKit',
    slug: 'esp32-s3-devkit',
    sku: 'SKU-MC-05',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248404/awie_store/microcontrollers/esp32-s3-devkit/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248404/awie_store/microcontrollers/esp32-s3-devkit/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248405/awie_store/microcontrollers/esp32-s3-devkit/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248403/awie_store/microcontrollers/esp32-s3-devkit/gpio-view.jpg'
    ],
    description: 'ESP32-S3 DevKit is an advanced development board powered by Espressif’s dual-core Xtensa LX7 processor with vector instructions for AI/ML edge computing (TinyML, speech recognition, face detection). Features dual USB ports (Native USB OTG + UART), 8 MB Flash, and Bluetooth 5 LE.',
    features: [
      'Dual-Core Xtensa LX7 32-bit CPU running up to 240 MHz',
      'Vector expansion instructions for hardware AI / ML acceleration',
      '512 KB SRAM, 384 KB ROM, 8 MB SPI Flash (with optional PSRAM support)',
      '2.4 GHz Wi-Fi 802.11 b/g/n & Bluetooth 5 (LE) with Long Range support',
      'Dual USB ports: 1x Native USB 1.1 OTG + 1x USB-to-UART Bridge',
      'Up to 45 GPIO pins with 14 Capacitive Touch channels & 20 ADC channels',
      'Interfaces: SPI, I2C, I2S, UART, PWM, SD/MMC, TWAI (CAN 2.0)'
    ],
    specs: {
      'CPU': 'Dual-Core Xtensa LX7 (240 MHz)',
      'AI Accelerator': 'Vector Instructions for Neural Networks',
      'SRAM / Flash': '512 KB SRAM / 8 MB SPI Flash',
      'Wi-Fi': '2.4 GHz 802.11 b/g/n',
      'Bluetooth': 'Bluetooth 5.0 LE & Long Range',
      'USB Interface': 'Dual USB (Native USB OTG + UART Bridge)',
      'GPIO Count': 'Up to 45 GPIO Pins',
      'Touch Sensing': '14 Touch Capacitive Pins',
      'ADC Inputs': '20 Channels (12-bit)',
      'Board Size': '62.0 × 28.0 × 13.0 mm'
    }
  },

  // 6. ESP32-CAM
  {
    id: 'mc-6',
    name: 'ESP32-CAM Vision & Wi-Fi Board',
    slug: 'esp32-cam',
    sku: 'SKU-MC-06',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248401/awie_store/microcontrollers/esp32-cam/side-viwe.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248401/awie_store/microcontrollers/esp32-cam/side-viwe.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248402/awie_store/microcontrollers/esp32-cam/top-view.webp',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248400/awie_store/microcontrollers/esp32-cam/gpio-view.png'
    ],
    description: 'ESP32-CAM is a compact development board featuring an ESP32 MCU, 4 MB external PSRAM, an onboard MicroSD slot, an ultra-bright White LED flash, and an OV2640 2 MP camera module. Perfect for wireless video streaming, AI face recognition, face tracking, and IoT surveillance.',
    features: [
      'Dual-Core ESP32 processor up to 240 MHz with Wi-Fi & BLE',
      'Includes OV2640 2 Megapixel camera module (UXGA 1600 × 1200 resolution)',
      '4 MB External IPUS PSRAM for high-resolution JPEG frame buffering',
      'Onboard MicroSD card socket (supports up to 4 GB SPI mode storage)',
      'Ultra-bright onboard White LED Flashlight (GPIO4 controlled)',
      'Supports JPEG, BMP, and Grayscale image capture formats',
      'Low power sleep modes down to 6 mA in deep sleep'
    ],
    specs: {
      'MCU': 'ESP32 Dual-Core @ 240 MHz',
      'Camera Sensor': 'OV2640 (2 Megapixel included)',
      'Max Resolution': '1600 × 1200 (UXGA)',
      'PSRAM': '4 MB External PSRAM',
      'Storage': 'MicroSD Slot (Up to 4 GB)',
      'Wi-Fi / BT': '2.4 GHz 802.11 b/g/n + Bluetooth 4.2 BLE',
      'Flash LED': 'Ultra-bright White LED (GPIO4)',
      'Power Supply': '5 V DC / 2 A Recommended',
      'Dimensions': '27.0 × 40.5 × 4.5 mm'
    }
  },

  // 7. ESP8266 NodeMCU
  {
    id: 'mc-7',
    name: 'ESP8266 NodeMCU V2',
    slug: 'esp8266-nodemcu',
    sku: 'SKU-MC-07',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/top-view.webp',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248405/awie_store/microcontrollers/esp8266-nodemcu/gpio-view.webp'
    ],
    description: 'ESP8266 NodeMCU V2 is an open-source Wi-Fi development board built around the ESP8266EX SoC. Featuring 4 MB SPI flash, an onboard CP2102/CH340 USB-to-UART bridge, and 10 GPIO pins, it provides an affordable entry into Wi-Fi IoT projects, Home Assistant integration, and Arduino IDE programming.',
    features: [
      'Tensilica Xtensa 32-bit single-core L106 processor @ 80 / 160 MHz',
      'Integrated 802.11 b/g/n Wi-Fi transceiver (2.4 GHz, WPA/WPA2)',
      '4 MB SPI Flash memory (Winbond 25Q32)',
      'Onboard USB-to-UART converter for plug-and-play programming',
      '17x GPIO pins (10x PWM enabled, SPI, I2C, UART support)',
      '1x 10-bit ADC channel (0 – 3.3V via onboard divider)',
      'Breadboard-friendly 30-pin form factor'
    ],
    specs: {
      'SoC': 'ESP8266EX (32-Bit @ 80/160 MHz)',
      'Flash Memory': '4 MB SPI Flash',
      'SRAM': '64 KB Instruction / 96 KB Data',
      'Wi-Fi Standard': '2.4 GHz 802.11 b/g/n',
      'USB Interface': 'CP2102 / CH340 Bridge',
      'Digital I/O': '17 Pins (10 PWM)',
      'Analog Input': '1 Channel (10-bit ADC)',
      'Operating Voltage': '3.3 V Logic (5 V USB/VIN)',
      'Dimensions': '48.0 × 25.0 × 13.0 mm'
    }
  },

  // 8. Arduino UNO R3 Compatible
  {
    id: 'mc-8',
    name: 'Arduino UNO R3 Compatible Board',
    slug: 'arduino-uno-r3',
    sku: 'SKU-MC-08',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-uno-r3/top-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-uno-r3/top-view.jpg'
    ],
    description: 'Arduino UNO R3 Compatible Development Board based on the Microchip ATmega328P 8-bit AVR microcontroller. Featuring 14 digital I/O pins, 6 analog inputs, a 16 MHz crystal oscillator, USB Type-B port, and DC barrel jack, this board is the gold standard for electronics learning, robotics, and prototyping.',
    features: [
      'ATmega328P 8-bit AVR RISC microcontroller operating at 16 MHz',
      '14 Digital Input/Output pins (6 PWM outputs: D3, D5, D6, D9, D10, D11)',
      '6 Analog Input channels (A0 to A5 with 10-bit ADC resolution)',
      '32 KB Flash memory (0.5 KB used by Optiboot bootloader), 2 KB SRAM, 1 KB EEPROM',
      '5 V DC operating logic level',
      'CH340G / ATmega16U2 USB interface for seamless PC communication',
      'DC Barrel Jack input supporting 7–12 V DC power supply'
    ],
    specs: {
      'Microcontroller': 'ATmega328P (8-Bit AVR)',
      'Clock Speed': '16 MHz Crystal',
      'Flash Memory': '32 KB (0.5 KB Bootloader)',
      'SRAM / EEPROM': '2 KB SRAM / 1 KB EEPROM',
      'Digital I/O Pins': '14 (6 PWM Channels)',
      'Analog Inputs': '6 Channels (10-bit ADC)',
      'Operating Voltage': '5 V DC Logic',
      'Input Voltage (Recommended)': '7 V – 12 V DC (Barrel Jack / VIN)',
      'USB Connector': 'USB Type-B Standard',
      'Board Dimensions': '68.6 × 53.4 mm'
    }
  },

  // 9. Arduino Nano R3 Compatible
  {
    id: 'mc-9',
    name: 'Arduino Nano R3 Compatible Board',
    slug: 'arduino-nano',
    sku: 'SKU-MC-09',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248391/awie_store/microcontrollers/arduino-nano-r3/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248391/awie_store/microcontrollers/arduino-nano-r3/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-nano-r3/top-view.jpg'
    ],
    description: 'Arduino Nano R3 Compatible is a compact, breadboard-friendly development board based on the ATmega328P microcontroller. Offering 22 I/O pins (including 8 analog inputs) in a tiny 45 × 18 mm layout, it provides full UNO functionality in a miniature footprint.',
    features: [
      'ATmega328P 8-bit AVR RISC processor @ 16 MHz',
      'Breadboard-friendly 30-pin dual inline package layout',
      '14 Digital I/O pins (6 PWM channels)',
      '8 Analog Input channels (A0 to A7, 10-bit ADC resolution)',
      '32 KB Flash memory, 2 KB SRAM, 1 KB EEPROM',
      '5 V DC operating logic level',
      'Mini-USB / USB Type-C connector with CH340G USB interface'
    ],
    specs: {
      'Microcontroller': 'ATmega328P (8-Bit AVR)',
      'Clock Speed': '16 MHz',
      'Flash Memory': '32 KB (2 KB Bootloader)',
      'SRAM / EEPROM': '2 KB SRAM / 1 KB EEPROM',
      'Digital I/O': '14 Pins (6 PWM)',
      'Analog Inputs': '8 Channels (10-bit ADC)',
      'Logic Voltage': '5 V DC',
      'Input Voltage (VIN)': '7 V – 12 V DC',
      'USB Connector': 'Mini-USB / USB Type-C',
      'Board Dimensions': '45.0 × 18.0 mm (Weight ~7 g)'
    }
  },

  // 2. Sensors (10 Items)
  {
    id: 'sn-1',
    name: 'HC-SR04 Ultrasonic Distance Sensor',
    slug: 'hc-sr04-ultrasonic-sensor',
    sku: 'SKU-SN-01',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256080/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256080/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_back-jpg.jpg'
    ],
    description: 'HC-SR04 is an ultrasonic distance-measuring module designed for obstacle detection, distance measurement and robotics applications.',
    features: [
      '2cm to 400cm typical measuring range with 3mm precision',
      '5 V DC operation at 40 kHz frequency',
      '4-pin interface (VCC, Trig, Echo, GND)',
      'Ideal for robot obstacle avoidance, distance measurement, and parking prototypes'
    ],
    specs: {
      'Sensor Type': 'Ultrasonic',
      'Operating Voltage': '5 V DC',
      'Frequency': '40 kHz',
      'Typical Measuring Range': '2–400 cm',
      'Interface': 'VCC, Trig, Echo, GND',
      'Output': 'Echo pulse',
      'Board Width': '40 mm',
      'Board Height': '20 mm',
      'Side Height': '15 mm'
    }
  },
  {
    id: 'sn-2',
    name: 'Infrared IR Obstacle Avoidance Sensor Module',
    slug: 'ir-obstacle-sensor',
    sku: 'SKU-SN-02',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_top-view-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_top-view-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_side-view-jpg.jpg'
    ],
    description: 'An infrared obstacle-detection module that detects nearby objects using reflected infrared light and provides a digital output.',
    features: [
      'Infrared reflective proximity sensor with 2–30 cm detection range',
      '35° detection angle with onboard sensitivity potentiometer adjustment',
      'LM393 voltage comparator with active low digital output',
      'Includes mounting screw holes for line-following robots and proximity automation'
    ],
    specs: {
      'Sensor Type': 'Infrared reflective',
      'Detection Range': '2–30 cm',
      'Detection Angle': '35°',
      'Comparator': 'LM393',
      'Output': 'Digital',
      'Output Logic': 'Active Low',
      'Adjustment': 'Sensitivity adjustable',
      'Mounting': 'Screw holes'
    }
  },
  {
    id: 'sn-3',
    name: 'HC-SR501 PIR Motion Sensor',
    slug: 'pir-motion-sensor',
    sku: 'SKU-SN-03',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256082/awie_store/sensors/hc-sr501-pir-motion-sensor_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256082/awie_store/sensors/hc-sr501-pir-motion-sensor_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256081/awie_store/sensors/hc-sr501-pir-motion-sensor_back-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256083/awie_store/sensors/hc-sr501-pir-motion-sensor_gpio-info-jpg.jpg'
    ],
    description: 'HC-SR501 is a passive infrared motion sensor module designed to detect movement of people and other warm objects.',
    features: [
      '3–7 m adjustable detection distance with <140° detection angle',
      'Ultra-low current drain (<60 µA) with 4.5–20 V DC wide supply voltage',
      '2.5 s default blockade/delay time',
      'Operating temperature range from −20°C to +80°C'
    ],
    specs: {
      'Sensor Type': 'PIR',
      'Operating Voltage': '4.5–20 V DC',
      'Current Drain': '<60 µA',
      'Detection Distance': '3–7 m, adjustable',
      'Detection Angle': '<140°',
      'Default Blockade/Delay': '2.5 s',
      'Operating Temperature': '−20°C to +80°C',
      'Output': 'Digital motion signal'
    }
  },
  {
    id: 'sn-4',
    name: 'LDR Light Sensor Module — LM393',
    slug: 'ldr-sensor-module',
    sku: 'SKU-SN-04',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Optical & Sound',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256085/awie_store/sensors/ldr-light-sensor-module_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256085/awie_store/sensors/ldr-light-sensor-module_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256086/awie_store/sensors/ldr-light-sensor-module_top-info-jpg.jpg'
    ],
    description: 'An LDR-based light sensor module for detecting ambient light intensity. It provides both analog and digital outputs and includes adjustable sensitivity.',
    features: [
      'Photoresistor / LDR sensor element with LM393 voltage comparator',
      '3.3–5 V DC operating range with dual Digital (DO) & Analog (AO) output pins',
      'Adjustable sensitivity potentiometer for setting light detection threshold',
      'Compact 33 × 14 × 8 mm footprint (4 g weight) for smart lamps and ambient light automation'
    ],
    specs: {
      'Sensor': 'LDR / Photoresistor',
      'Comparator': 'LM393',
      'Operating Voltage': '3.3–5 V',
      'Digital Output': 'DO',
      'Analog Output': 'AO',
      'Sensitivity': 'Adjustable potentiometer',
      'Length': '33 mm',
      'Width': '14 mm',
      'Height': '8 mm',
      'Weight': '4 g'
    }
  },
  {
    id: 'sn-5',
    name: 'DHT11 Digital Temperature & Humidity Sensor',
    slug: 'dht11-sensor',
    sku: 'SKU-SN-05',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht11-temperature-humidity-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht11-temperature-humidity-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256074/awie_store/sensors/dht11-temperature-humidity-sensor_side-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256074/awie_store/sensors/dht11-temperature-humidity-sensor_gpio-jpg.jpg'
    ],
    description: 'DHT11 is a low-cost digital sensor for measuring ambient temperature and relative humidity.',
    features: [
      '0–50°C temperature range (±2°C accuracy)',
      '20–90% RH relative humidity range (±5% RH accuracy)',
      '16-bit digital output with 1 Hz sampling rate',
      '3–5 V supply with single-wire digital interface'
    ],
    specs: {
      'Sensor Type': 'Digital temperature + humidity',
      'Supply': '3–5 V',
      'Temperature Range': '0–50°C',
      'Temperature Accuracy': '±2°C',
      'Humidity Range': '20–90% RH',
      'Humidity Accuracy': '±5% RH',
      'Resolution': '16-bit digital output',
      'Sampling': 'Up to 1 Hz',
      'Interface': 'Single-wire digital'
    }
  },
  {
    id: 'sn-6',
    name: 'DHT22 / AM2302 Digital Temperature & Humidity Sensor',
    slug: 'dht22-sensor',
    sku: 'SKU-SN-06',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256077/awie_store/sensors/dht22-am2302-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256077/awie_store/sensors/dht22-am2302-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht22-am2302-sensor_back-jpg.jpg'
    ],
    description: 'DHT22 is a digital temperature and humidity sensor offering higher measurement range and accuracy than the basic DHT11.',
    features: [
      '−40 to +80°C temperature range with ±0.5°C accuracy',
      '0–99.9% RH humidity range with ±2% RH accuracy',
      'High 0.1°C / 0.1% RH resolution',
      'Calibrated single-wire digital output for HVAC and weather station prototypes'
    ],
    specs: {
      'Sensor Type': 'Digital temperature + humidity',
      'Model': 'DHT22 / AM2302',
      'Temperature Range': '−40 to +80°C',
      'Humidity Range': '0–99.9% RH',
      'Temperature Accuracy': '±0.5°C',
      'Humidity Accuracy': '±2% RH around 10–90% RH',
      'Temperature Resolution': '0.1°C',
      'Humidity Resolution': '0.1% RH',
      'Output': 'Calibrated digital signal',
      'Interface': 'Single-wire digital'
    }
  },
  {
    id: 'sn-7',
    name: 'DS18B20 Waterproof Temperature Sensor Probe',
    slug: 'ds18b20-temperature-sensor',
    sku: 'SKU-SN-07',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/ds18b20-temperature-sensor-prob_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/ds18b20-temperature-sensor-prob_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256078/awie_store/sensors/ds18b20-temperature-sensor-prob_gipo-info-jpg.jpg'
    ],
    description: 'Waterproof digital temperature sensor probe with a stainless-steel housing and 1-Wire interface, suitable for liquid, outdoor, IoT and embedded temperature monitoring.',
    features: [
      'Waterproof stainless-steel probe (approx. 6 mm × 45–50 mm) with sealed housing',
      '1-Wire interface — only one data pin required, supports multi-sensor bus',
      '−55°C to +125°C range with ±0.5°C accuracy, 9–12-bit programmable resolution',
      'Long ~1 m 3-wire cable — suitable for aquarium, soil, liquid, and outdoor environments'
    ],
    specs: {
      'Sensor IC': 'DS18B20',
      'Sensor Type': 'Digital temperature sensor',
      'Interface': '1-Wire',
      'Operating Voltage': '3.0–5.5 V',
      'Temperature Range': '−55°C to +125°C',
      'Accuracy': '±0.5°C from −10°C to +85°C',
      'Resolution': '9-bit to 12-bit programmable',
      'Probe Material': 'Stainless steel',
      'Probe Diameter': 'Approx. 6 mm',
      'Probe Length': 'Approx. 45–50 mm',
      'Cable Length': 'Approx. 1 metre',
      'Cable': '3-wire (Red=VCC, Black=GND, Yellow/White=DATA)',
      'Waterproof': 'Yes — sealed probe',
      'Pull-up resistor': '4.7 kΩ recommended',
      'Conversion Time': 'Up to 750 ms at 12-bit',
      'Unique ID': '64-bit'
    }
  },
  {
    id: 'sn-8',
    name: 'MQ-2 Smoke, LPG & Gas Sensor Module',
    slug: 'mq-2-gas-sensor',
    sku: 'SKU-SN-08',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256089/awie_store/sensors/mq-2-gas-sensor-module_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256089/awie_store/sensors/mq-2-gas-sensor-module_top-jpg.jpg'
    ],
    description: 'MQ-2 is a gas-sensing module commonly used in electronics projects for detecting smoke and several combustible gases.',
    features: [
      'Detects smoke, LPG, butane, hydrogen, and combustible gas concentrations',
      'Dual signal outputs: 0–5 V Analog + TTL Digital',
      'Onboard potentiometer sensitivity threshold adjustment',
      'Compact 36 × 20 × 21 mm breakout board'
    ],
    specs: {
      'Sensor Type': 'Semiconductor gas sensor',
      'Operating Voltage': '5 V',
      'Preheat Duration': '~20 s',
      'Analog Output': '0–5 V',
      'Digital Output': 'TTL',
      'Module Dimensions': '36 × 20 × 21 mm',
      'Detectable gases': 'Smoke, LPG, butane, hydrogen and other combustible gases',
      'Sensitivity': 'Adjustable on module'
    }
  },
  {
    id: 'sn-9',
    name: 'MPU-6050 6-Axis Accelerometer & Gyroscope Module',
    slug: 'mpu-6050-gyroscope',
    sku: 'SKU-SN-09',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256088/awie_store/sensors/mpu-6050_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256088/awie_store/sensors/mpu-6050_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256087/awie_store/sensors/mpu-6050_side-jpg.jpg'
    ],
    description: 'MPU-6050 combines a 3-axis accelerometer and 3-axis gyroscope in one motion-sensing device for orientation, movement and motion-monitoring projects.',
    features: [
      '6-axis motion tracking (3-axis Gyroscope + 3-axis Accelerometer)',
      'User-programmable gyro range: ±250 / ±500 / ±1000 / ±2000 °/s',
      'User-programmable accel range: ±2g / ±4g / ±8g / ±16g',
      'Standard I2C digital interface for robotics, drones, and orientation tracking'
    ],
    specs: {
      'Sensor': '3-axis accelerometer + 3-axis gyroscope',
      'Axes': '6-axis motion sensing',
      'Interface': 'I²C',
      'Accelerometer': '±2g / ±4g / ±8g / ±16g',
      'Gyroscope': '±250 / ±500 / ±1000 / ±2000 °/s',
      'Digital Interface': 'I²C',
      'Applications': 'Motion/orientation sensing'
    }
  },
  {
    id: 'sn-10',
    name: 'SW-420 Vibration Sensor Module',
    slug: 'sw-420-vibration-sensor',
    sku: 'SKU-SN-10',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256091/awie_store/sensors/sw-420-vibration-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256091/awie_store/sensors/sw-420-vibration-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256090/awie_store/sensors/sw-420-vibration-sensor_side-jpg.jpg'
    ],
    description: 'SW-420 is a vibration detection module that detects vibration or movement and provides a digital switching output.',
    features: [
      'SW-420 normally-closed vibration sensor element',
      'LM393 comparator with adjustable sensitivity potentiometer',
      '3.3–5 V DC operating range with digital switching output (0/1)',
      'Mounting bolt holes for anti-tamper alarms and machine monitoring'
    ],
    specs: {
      'Sensor': 'SW-420 normally-closed vibration sensor',
      'Comparator': 'LM393',
      'Operating Voltage': '3.3–5 V',
      'Output': 'Digital',
      'Output Logic': '0 / 1 switching',
      'Sensitivity': 'Adjustable',
      'Mounting': 'Bolt holes',
      'Output Drive': '>15 mA'
    }
  },

  // 3. Modules (10 Items)
  {
    id: 'md-1',
    name: '5V 1-Channel Relay Module',
    slug: 'relay-5v-single',
    sku: 'SKU-MD-01',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Single-channel 5V relay module for controlling higher-voltage or higher-current loads using Arduino, ESP32, ESP8266 and other microcontrollers.',
    features: [
      'Single electromechanical relay with COM, NO, NC screw terminals',
      '5V coil voltage with digital input control',
      'Power and status LED indicators onboard',
      'Compatible with Arduino, ESP32, ESP8266, and Raspberry Pi'
    ],
    specs: {
      'Channels': '1',
      'Relay Coil Voltage': '5 V DC',
      'Relay Type': 'Electromechanical',
      'Control': 'Digital input',
      'Relay Contacts': 'COM, NO, NC',
      'Typical Contact Rating': 'Up to 10 A',
      'Indicator': 'Power/status LED',
      'Interface': 'VCC, GND, IN'
    }
  },
  {
    id: 'md-2',
    name: '5V 4-Channel Relay Module',
    slug: 'relay-5v-4ch',
    sku: 'SKU-MD-02',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Four-channel 5V relay module for independently switching multiple electrical loads from a microcontroller or development board.',
    features: [
      '4 independent electromechanical relays with individual IN1–IN4 control pins',
      '5V coil voltage with COM/NO/NC screw terminals per channel',
      'Individual LED indicator per relay channel',
      'Suitable for home automation, robotics, and multi-load switching projects'
    ],
    specs: {
      'Channels': '4',
      'Coil Voltage': '5 V DC',
      'Relay Type': 'Electromechanical',
      'Inputs': 'IN1–IN4',
      'Contacts': 'COM / NO / NC',
      'Indicator': 'Individual channel LEDs',
      'Power': '5 V DC'
    }
  },
  {
    id: 'md-3',
    name: 'TP4056 1A Li-Ion Charger Module with Protection',
    slug: 'tp4056-charger',
    sku: 'SKU-MD-03',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Compact single-cell lithium-ion battery charging module based on TP4056, designed for charging 3.7V Li-ion/Li-Po cells from a 5V USB supply.',
    features: [
      'TP4056 controller with up to 1A constant-current charging',
      'Integrated battery protection circuit (overcharge, over-discharge)',
      'Charging and full-charge status indicator LEDs',
      'Micro-USB 5V input — suitable for portable electronics and ESP32 power systems'
    ],
    specs: {
      'Controller': 'TP4056',
      'Battery': '1-cell Li-Ion/Li-Po',
      'Nominal Battery': '3.7 V',
      'Charge Voltage': '4.2 V',
      'Charge Current': 'Up to 1 A',
      'Input': '5 V',
      'Input Connector': 'Micro-USB',
      'Protection': 'Overcharge & over-discharge circuit',
      'Charging LED': 'Yes',
      'Full LED': 'Yes'
    }
  },
  {
    id: 'md-4',
    name: 'NRF24L01 2.4GHz Wireless Transceiver Module',
    slug: 'nrf24l01-wireless',
    sku: 'SKU-MD-04',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Compact 2.4GHz wireless transceiver module for low-power bidirectional communication between microcontrollers.',
    features: [
      'nRF24L01+ IC with 2.4 GHz ISM band operation',
      'SPI interface with up to 2 Mbps data rate',
      '1.9–3.6 V supply with up to 125 configurable channels',
      'Integrated PCB antenna — suitable for sensor networks, RC, and IoT projects'
    ],
    specs: {
      'IC': 'nRF24L01+',
      'Frequency': '2.4 GHz ISM',
      'Communication': 'SPI',
      'Data Rate': '250 kbps / 1 Mbps / 2 Mbps',
      'Supply Voltage': '1.9–3.6 V',
      'Logic': '3.3 V',
      'Channels': 'Up to 125',
      'Antenna': 'Integrated PCB antenna'
    }
  },
  {
    id: 'md-5',
    name: 'HC-05 Bluetooth Serial Communication Module',
    slug: 'hc-05-bluetooth',
    sku: 'SKU-MD-05',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'HC-05 is a Bluetooth Classic serial communication module commonly used to add wireless UART connectivity to microcontroller projects.',
    features: [
      'Bluetooth Classic SPP profile with master and slave mode support',
      'UART serial interface (TX, RX, VCC, GND) — drop-in wireless serial replacement',
      'Configurable via AT commands for baud rate, name, and pairing mode',
      'Typical ~10 m range for robot control, data telemetry, and wireless projects'
    ],
    specs: {
      'Module': 'HC-05',
      'Bluetooth': 'Classic Bluetooth',
      'Bluetooth Version': '2.0 + EDR',
      'Profile': 'SPP',
      'Communication': 'UART',
      'Operating Logic': '3.3 V',
      'Modes': 'Master/Slave capable',
      'Interface': 'TX, RX, VCC, GND'
    }
  },
  {
    id: 'md-6',
    name: 'NEO-6M GPS Module with Antenna',
    slug: 'neo-6m-gps',
    sku: 'SKU-MD-06',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 599,
    originalPrice: 599,
    discountPercent: 0,
    inStock: true,
    stockCount: 80,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'NEO-6M GPS module for receiving satellite positioning data and providing location information to Arduino, ESP32 and other microcontrollers.',
    features: [
      'u-blox NEO-6M GPS receiver with UART serial interface',
      'External ceramic GPS antenna included',
      'Outputs NMEA-format data: latitude, longitude, altitude, speed, time',
      'GPS status indicator LED — used for drones, trackers, and navigation projects'
    ],
    specs: {
      'GPS Receiver': 'u-blox NEO-6M',
      'GNSS': 'GPS',
      'Interface': 'UART',
      'Communication': 'Serial',
      'Antenna': 'External ceramic GPS antenna',
      'Position Data': 'Latitude, longitude, altitude, time',
      'Protocol': 'NMEA'
    }
  },
  {
    id: 'md-7',
    name: 'DS3231 Precision RTC Module with AT24C32 EEPROM',
    slug: 'ds3231-rtc',
    sku: 'SKU-MD-07',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'High-accuracy real-time clock module using the DS3231 with I²C communication, battery backup and onboard AT24C32 EEPROM.',
    features: [
      'DS3231 temperature-compensated RTC with I²C interface (3.3–5 V)',
      'Battery backup CR2032 coin cell holder for power-loss timekeeping',
      'AT24C32 32 kbit onboard EEPROM for data storage',
      '2 programmable alarms and configurable square-wave output'
    ],
    specs: {
      'RTC IC': 'DS3231',
      'Interface': 'I²C',
      'Supply': '3.3–5 V',
      'Clock': 'Seconds, minutes, hours',
      'Calendar': 'Day, date, month, year',
      'Leap Year': 'Automatic',
      'Battery Backup': 'Yes',
      'EEPROM': 'AT24C32, 32 kbit',
      'Accuracy': 'Temperature-compensated RTC',
      'Alarm': '2 programmable alarms'
    }
  },
  {
    id: 'md-8',
    name: 'PAM8403 5V Stereo Class-D 3W + 3W Audio Amplifier Module',
    slug: 'pam8403-audio',
    sku: 'SKU-MD-08',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 120,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Compact stereo Class-D audio amplifier module designed to drive small speakers from a low-voltage 5V supply.',
    features: [
      'PAM8403 Class-D stereo amplifier IC with up to 3W + 3W output',
      '5V USB-powered — no heatsink required at typical load levels',
      'Left and right speaker screw terminal outputs',
      'High efficiency Class-D design for Arduino and ESP32 audio projects'
    ],
    specs: {
      'IC': 'PAM8403',
      'Amplifier Type': 'Class-D',
      'Channels': '2',
      'Output': 'Up to 3 W + 3 W',
      'Supply': '5 V',
      'Input': 'Analog audio',
      'Speaker Output': 'Left + Right'
    }
  },
  {
    id: 'md-9',
    name: 'MAX485 TTL to RS485 Communication Module',
    slug: 'max485-rs485',
    sku: 'SKU-MD-09',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'TTL-to-RS485 interface module for connecting microcontrollers to long-distance differential serial communication networks.',
    features: [
      'MAX485 transceiver IC for TTL UART to RS485 differential conversion',
      'Half-duplex communication with DE/RE direction control pins',
      '5 V supply — suitable for Arduino and ESP32 Modbus RTU projects',
      'Differential A/B bus terminals for long-distance industrial communication'
    ],
    specs: {
      'IC': 'MAX485',
      'Protocol': 'RS485',
      'Interface': 'TTL UART',
      'Supply': '5 V',
      'Communication': 'Half-duplex',
      'Bus': 'Differential A/B',
      'Direction Control': 'DE / RE'
    }
  },
  {
    id: 'md-10',
    name: '4-Channel Bidirectional Logic Level Converter 3.3V ↔4 5V',
    slug: 'logic-level-converter',
    sku: 'SKU-MD-10',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Bidirectional logic-level converter for safely interfacing 3.3V and 5V digital electronics.',
    features: [
      '4-channel bidirectional level shifting between 3.3V and 5V logic',
      'Protects 3.3V devices from 5V signals — essential for ESP32/ESP8266 interfacing',
      'LV (3.3V) and HV (5V) power supply pins with common GND',
      'Compact breakout suitable for I2C, SPI, and UART signal conversion'
    ],
    specs: {
      'Channels': '4',
      'Direction': 'Bidirectional',
      'Low Voltage Side': '3.3 V',
      'High Voltage Side': '5 V',
      'Interface': 'Digital signal conversion',
      'Typical Use': 'MCU-to-module interfacing',
      'Type': 'Logic-level shifter'
    }
  },
  {
    id: 'md-2',
    name: 'TP4056 Charging Module',
    slug: 'tp4056-charging-module',
    sku: 'SKU-MD-02',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1A Lithium battery charging module with dual protection IC and Micro-USB / Type-C input.',
    features: ['1A constant current charging', 'Overcharge & over-discharge protection', 'Status indicator LEDs'],
    specs: { 'Charge Current': '1A Adjustable', 'Input Interface': 'USB Type-C' }
  },
  {
    id: 'md-3',
    name: 'TP4050 Charging Module',
    slug: 'tp4050-charging-module',
    sku: 'SKU-MD-03',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Linear Li-Ion battery charger board supporting high current thermal management.',
    features: ['Up to 1A programmable charge rate', 'Soft-start limits inrush current', 'LED status lights'],
    specs: { 'Input Voltage': '4.5V - 6V', 'Max Current': '1000mA' }
  },
  {
    id: 'md-4',
    name: '5V Relay Module',
    slug: '5v-relay-module',
    sku: 'SKU-MD-04',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Standard 5V single channel relay module with optocoupler isolation for switching AC 250V / DC 30V loads.',
    features: ['Optocoupler isolation', 'High current relay AC250V 10A', 'Status LED indicator'],
    specs: { 'Control Voltage': '5V DC', 'Max Load': 'AC 250V 10A / DC 30V 10A' }
  },
  {
    id: 'md-5',
    name: '1-Channel Relay Module',
    slug: '1-channel-relay',
    sku: 'SKU-MD-05',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Single channel isolated relay switch for high voltage appliance control.',
    features: ['NO/NC terminal blocks', 'Low level trigger support'],
    specs: { 'Trigger Current': '5mA', 'Voltage': '5V' }
  },
  {
    id: 'md-6',
    name: '2-Channel Relay Module',
    slug: '2-channel-relay',
    sku: 'SKU-MD-06',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Dual channel 5V relay board for controlling two separate electrical circuits independently.',
    features: ['Dual optocouplers', 'Independent control lines', 'Screw terminal blocks'],
    specs: { 'Channels': '2', 'Max Current': '10A per channel' }
  },
  {
    id: 'md-7',
    name: '4-Channel Relay Module',
    slug: '4-channel-relay',
    sku: 'SKU-MD-07',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 169,
    originalPrice: 169,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Quad channel relay board equipped with optical isolation for home automation systems.',
    features: ['4 independent relays', 'Red LED channel indicators', 'Microcontroller compatible trigger'],
    specs: { 'Channels': '4', 'Rating': '10A 250VAC / 10A 30VDC' }
  },
  {
    id: 'md-8',
    name: 'L298N Motor Driver Module',
    slug: 'l298n-motor-driver-module',
    sku: 'SKU-MD-08',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-bridge motor driver module capable of driving two DC motors or one 4-wire stepper motor.',
    features: ['High power L298N IC', 'Aluminum heatsink onboard', '5V onboard regulator'],
    specs: { 'Motor Supply Voltage': '5V - 35V', 'Peak Current': '2A per bridge' }
  },
  {
    id: 'md-9',
    name: 'DRV8833 Motor Driver Module',
    slug: 'drv8833-motor-driver-module',
    sku: 'SKU-MD-09',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual MOSFET H-bridge motor driver module featuring low power loss for battery-operated mini robots.',
    features: ['Dual H-bridge driver', 'Low RDS(on) MOSFETs', 'Built-in thermal shutdown'],
    specs: { 'Operating Voltage': '2.7V - 10.8V', 'Output Current': '1.5A per channel' }
  },
  {
    id: 'md-10',
    name: 'TB6612FNG Motor Driver Module',
    slug: 'tb6612fng-motor-driver-module',
    sku: 'SKU-MD-10',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'High-efficiency dual DC motor driver module based on Toshiba TB6612FNG MOSFET bridge.',
    features: ['Higher efficiency than L298N', '1.2A continuous current per channel', 'Standby mode for power saving'],
    specs: { 'Supply Voltage': '15V Max', 'Continuous Current': '1.2A per channel' }
  },
  {
    id: 'md-11',
    name: 'MAX98357A I2S Audio Amplifier Module',
    slug: 'max98357a-i2s-amplifier',
    sku: 'SKU-MD-11',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Digital I2S Class-D mono audio amplifier module producing 3.2W output into a 4-ohm speaker for ESP32 sound projects.',
    features: ['Direct digital I2S input', '3.2W Class-D amplifier', 'No external MCLK required'],
    specs: { 'Output Power': '3.2W into 4Ω', 'Operating Voltage': '2.5V - 5.5V' }
  },
  {
    id: 'md-12',
    name: 'MicroSD Card Module',
    slug: 'microsd-card-module',
    sku: 'SKU-MD-12',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'SPI interface MicroSD card reader board with onboard 3.3V level converter for microcontroller data logging.',
    features: ['SPI interface protocol', 'Onboard 3.3V regulator', 'Level shifting buffer IC'],
    specs: { 'Interface': 'SPI', 'Card Supported': 'Micro SD <= 2GB, Micro SDHC <= 32GB' }
  },
  {
    id: 'md-13',
    name: 'Bluetooth HC-05 Module',
    slug: 'bluetooth-hc-05-module',
    sku: 'SKU-MD-13',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Master/Slave SPP (Serial Port Protocol) Bluetooth 2.0 module for wireless serial UART communication.',
    features: ['Master & Slave mode switchable', 'Default baud rate 9600', 'Onboard button for AT commands'],
    specs: { 'Bluetooth Protocol': 'V2.0+EDR', 'Operating Voltage': '3.6V - 6V' }
  },
  {
    id: 'md-14',
    name: 'Bluetooth HC-06 Module',
    slug: 'bluetooth-hc-06-module',
    sku: 'SKU-MD-14',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Slave-only Bluetooth serial transceiver module ideal for smartphone-to-microcontroller wireless control.',
    features: ['Slave mode configuration', 'Simple UART serial interface', 'Signal status LED'],
    specs: { 'Frequency': '2.4GHz ISM', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-15',
    name: 'ESP-NOW-Compatible ESP32 Boards',
    slug: 'esp-now-compatible-esp32',
    sku: 'SKU-MD-15',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'ESP32 development module configured for ultra-low latency connection-less ESP-NOW protocol peer-to-peer mesh.',
    features: ['Low latency peer-to-peer transmission', 'No router required', 'Configurable mesh firmware'],
    specs: { 'Protocol': 'ESP-NOW 2.4GHz', 'Range': 'Up to 200 meters line-of-sight' }
  },
  {
    id: 'md-16',
    name: 'Buzzer Module',
    slug: 'buzzer-module',
    sku: 'SKU-MD-16',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Active/Passive piezo buzzer driver board for audio tone generation and alert beeps.',
    features: ['S8050 transistor drive circuit', 'High sound pressure output', 'Digital pin activation'],
    specs: { 'Operating Voltage': '3.3V - 5V', 'Sound Frequency': '2.5kHz ± 300Hz' }
  },
  {
    id: 'md-17',
    name: 'RTC DS3231 Real-Time Clock Module',
    slug: 'rtc-ds3231-module',
    sku: 'SKU-MD-17',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Extremely accurate I2C real-time clock (RTC) module with integrated TCXO crystal and coin cell backup socket.',
    features: ['Integrated TCXO temperature compensated crystal', 'Battery backup coin cell holder', 'I2C interface with AT24C32 EEPROM'],
    specs: { 'Accuracy': '±2ppm', 'Interface': 'I2C' }
  },
  {
    id: 'md-18',
    name: 'Joystick Module',
    slug: 'joystick-module',
    sku: 'SKU-MD-18',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Dual-axis X/Y analog thumb joystick module with integrated push-button switch.',
    features: ['Two 10k potentiometers for X/Y axes', 'Integrated tactile click button', 'Standard 5-pin header'],
    specs: { 'Output': 'Dual Analog + Digital Push Switch', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-19',
    name: 'Voltage Sensor Module',
    slug: 'voltage-sensor-module',
    sku: 'SKU-MD-19',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Resistive voltage divider module that steps down input DC voltage up to 25V for 5V ADC microcontrollers.',
    features: ['5:1 voltage divider ratio', 'Measures up to 25V DC', 'Screw terminal blocks'],
    specs: { 'Max Input Voltage': '25V DC', 'Divider Ratio': '5:1' }
  },
  {
    id: 'md-20',
    name: 'Current Sensor Module',
    slug: 'current-sensor-module',
    sku: 'SKU-MD-20',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'ACS712 linear Hall-effect current sensor module for measuring AC and DC electrical load current up to 20A.',
    features: ['Hall-effect current sensing', 'Galvanic isolation', 'Low noise analog signal path'],
    specs: { 'Current Range': '20A Max', 'Sensitivity': '100mV/A' }
  },
  {
    id: 'md-21',
    name: 'Step-Down Buck Converter Module',
    slug: 'step-down-buck-converter',
    sku: 'SKU-MD-21',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 DC-DC adjustable step-down buck power module converting high input voltages down to 1.25V-30V.',
    features: ['LM2596 IC switcher', 'Trimmer potentiometer adjustment', 'Up to 3A output capability'],
    specs: { 'Input Voltage': '4V - 35V', 'Output Voltage': '1.23V - 30V' }
  },
  {
    id: 'md-22',
    name: 'Step-Up Boost Converter Module',
    slug: 'boost-converter-module',
    sku: 'SKU-MD-22',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 2A DC-DC step-up voltage boost converter board for stepping battery voltage up to 28V.',
    features: ['High 1.2MHz switching frequency', 'Compact footprint', 'Up to 93% conversion efficiency'],
    specs: { 'Input Voltage': '2V - 24V', 'Max Output Voltage': '28V DC' }
  },

  // 4. Displays (13 Items)
  {
    id: 'dp-1',
    name: '0.96" OLED 128×64 Display',
    slug: '0-96-oled-128x64',
    sku: 'SKU-DP-01',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: 'High-contrast monochrome I2C OLED display module with 128x64 resolution powered by SSD1306 driver chip.',
    features: ['SSD1306 driver controller', 'No backlight needed (self-illuminating)', 'I2C address 0x3C'],
    specs: { 'Resolution': '128x64', 'Interface': 'I2C', 'Color': 'Blue / White / Yellow-Blue' }
  },
  {
    id: 'dp-2',
    name: '1.3" OLED 128×64 Display',
    slug: '1-3-oled-128x64',
    sku: 'SKU-DP-02',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: 'Larger 1.3-inch graphic OLED display module with SH1106 controller and I2C serial interface.',
    features: ['SH1106 driver IC', 'Wide viewing angle > 160 degrees', 'Low power drain'],
    specs: { 'Screen Size': '1.3 Inch', 'Resolution': '128x64', 'Interface': 'I2C' }
  },
  {
    id: 'dp-3',
    name: '1.54" OLED Display',
    slug: '1-54-oled-display',
    sku: 'SKU-DP-03',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 399,
    originalPrice: 399,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: '1.54-inch full graphic OLED display module with SPI/I2C option for crisp UI dashboards.',
    features: ['SSD1309 controller', '128x64 high contrast display', 'SPI / I2C jumper selectable'],
    specs: { 'Size': '1.54 Inch', 'Driver': 'SSD1309' }
  },
  {
    id: 'dp-4',
    name: '1.8" TFT Display',
    slug: '1-8-tft-display',
    sku: 'SKU-DP-04',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 120,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '128x160 color TFT SPI LCD display module based on ST7735 driver with MicroSD card slot.',
    features: ['18-bit 262,000 full color spectrum', 'SPI bus interface', 'MicroSD slot on back'],
    specs: { 'Resolution': '128x160', 'Driver': 'ST7735', 'Interface': 'SPI' }
  },
  {
    id: 'dp-5',
    name: '2.4" TFT Display',
    slug: '2-4-tft-display',
    sku: 'SKU-DP-05',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 449,
    originalPrice: 449,
    discountPercent: 0,
    inStock: true,
    stockCount: 95,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '240x320 resolution SPI color TFT touchscreen LCD panel powered by ILI9341 controller.',
    features: ['ILI9341 controller IC', '240x320 RGB pixels', 'Resistive touch screen panel'],
    specs: { 'Resolution': '240x320', 'Driver': 'ILI9341' }
  },
  {
    id: 'dp-6',
    name: '2.8" TFT Display',
    slug: '2-8-tft-display',
    sku: 'SKU-DP-06',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 599,
    originalPrice: 599,
    discountPercent: 0,
    inStock: true,
    stockCount: 80,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '2.8-inch Arduino Uno shield format color TFT touchscreen module with SD slot.',
    features: ['Arduino Uno shield form factor', 'Built-in touch panel controller', 'MicroSD storage'],
    specs: { 'Screen Size': '2.8 Inch', 'Interface': '8-bit parallel / SPI' }
  },
  {
    id: 'dp-7',
    name: '3.5" TFT Display',
    slug: '3-5-tft-display',
    sku: 'SKU-DP-07',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 799,
    originalPrice: 799,
    discountPercent: 0,
    inStock: true,
    stockCount: 65,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '320x480 pixel high resolution 3.5-inch color TFT touchscreen display panel for ESP32 & Arduino Mega.',
    features: ['320x480 HD resolution', 'ILI9486 driver', 'Full color RGB 65K colors'],
    specs: { 'Resolution': '320x480', 'Driver': 'ILI9486' }
  },
  {
    id: 'dp-8',
    name: '16×2 LCD Display with I2C',
    slug: '16x2-lcd-display',
    sku: 'SKU-DP-08',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/lcd.svg',
    description: 'Blue backlight character 16x2 LCD display pre-soldered with PCF8574 I2C adapter backpack.',
    features: ['Pre-soldered I2C backpack module', 'Contrast trim potentiometer', 'Blue background white text'],
    specs: { 'Characters': '16 Cols x 2 Rows', 'Interface': 'I2C (Address 0x27 / 0x3F)' }
  },
  {
    id: 'dp-9',
    name: '20×4 LCD Display with I2C',
    slug: '20x4-lcd-display',
    sku: 'SKU-DP-09',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/lcd.svg',
    description: 'Large 20 column by 4 row character LCD module bundled with I2C bus backpack converter.',
    features: ['20x4 character matrix', '4-wire I2C interface connection', 'LED backlight switch jumper'],
    specs: { 'Matrix': '20x4 Characters', 'Backlight': 'Blue/Yellow-Green' }
  },
  {
    id: 'dp-10',
    name: '7-Segment LED Display',
    slug: '7-segment-display',
    sku: 'SKU-DP-10',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: '0.56-inch 4-digit 7-segment red LED display module with decimal points for digital clocks and counters.',
    features: ['4 digit multiplexed display', 'High brightness red LEDs', 'Common Cathode / Anode'],
    specs: { 'Digits': '4', 'Color': 'Red' }
  },
  {
    id: 'dp-11',
    name: 'MAX7219 8×8 LED Matrix',
    slug: 'max7219-8x8-led-matrix',
    sku: 'SKU-DP-11',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: 'MAX7219 serial input LED driver module connected to an 8x8 dot matrix display for scrolling text.',
    features: ['SPI serial communication', 'Cascadable modular design', 'Individual LED pixel control'],
    specs: { 'Matrix': '8x8 Pixels', 'Driver IC': 'MAX7219' }
  },
  {
    id: 'dp-12',
    name: 'WS2812B LED Strip',
    slug: 'ws2812b-led-strip',
    sku: 'SKU-DP-12',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED Lighting',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: '1-meter 60 LEDs WS2812B addressable RGB LED strip with individual Neopixel pixel control over single wire data pin.',
    features: ['Addressable Neopixel control', '5V DC operation', 'Integrated 5050 RGB LEDs'],
    specs: { 'Density': '60 LEDs/m', 'Voltage': '5V DC', 'Data Protocol': 'Single wire NZR' }
  },
  {
    id: 'dp-13',
    name: 'RGB LED Module',
    slug: 'rgb-led-module',
    sku: 'SKU-DP-13',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED Lighting',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: 'Full color 5050 SMD RGB LED breakout module with current limiting resistors for PWM color mixing.',
    features: ['Red, Green, Blue PWM channels', 'Common Cathode connection', 'Onboard limit resistors'],
    specs: { 'LED Type': '5050 SMD RGB', 'Voltage': '3.3V - 5V' }
  },

  // 5. Motors & Drivers (17 Items)
  {
    id: 'mt-1',
    name: 'SG90 Servo Motor',
    slug: 'sg90-servo-motor',
    sku: 'SKU-MT-01',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: '9g lightweight micro servo motor with 180-degree rotation, plastic gears, and mounting horns.',
    features: ['180 degree rotation angle', '1.8 kg/cm holding torque', 'Includes 3 servo horns'],
    specs: { 'Torque': '1.8 kg-cm @ 4.8V', 'Weight': '9 grams', 'Speed': '0.12 sec/60 deg' }
  },
  {
    id: 'mt-2',
    name: 'MG90S Servo Motor',
    slug: 'mg90s-servo-motor',
    sku: 'SKU-MT-02',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'Micro metal gear 9g servo motor offering increased durability and torque for robotic arms.',
    features: ['Full metal gear train', '2.2 kg/cm torque at 6V', 'Dual ball bearing'],
    specs: { 'Gears': 'Metal', 'Torque': '2.2 kg-cm' }
  },
  {
    id: 'mt-3',
    name: 'MG996R Servo Motor',
    slug: 'mg996r-servo-motor',
    sku: 'SKU-MT-03',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'High-torque standard size digital metal gear servo motor providing up to 11 kg/cm torque.',
    features: ['Metal internal gears', 'Heavy-duty 11 kg/cm torque', 'Double ball bearing shaft'],
    specs: { 'Torque': '11 kg-cm @ 6V', 'Rotation': '180 Degrees' }
  },
  {
    id: 'mt-4',
    name: '8520 Coreless Motor',
    slug: '8520-coreless-motor',
    sku: 'SKU-MT-04',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Ultra-fast 8.5x20mm micro coreless DC motor designed for micro quadcopters and lightweight RC models.',
    features: ['High speed 45,000 RPM @ 3.7V', 'Lightweight coreless design', 'Pre-wired leads'],
    specs: { 'Size': '8.5mm x 20mm', 'Voltage': '3.7V DC', 'Speed': '45000 RPM' }
  },
  {
    id: 'mt-5',
    name: 'TT Gear Motor',
    slug: 'tt-gear-motor',
    sku: 'SKU-MT-05',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual-axis plastic gearbox DC motor for smart robot car chassis with 1:48 gear ratio.',
    features: ['1:48 reduction gear ratio', 'EMC anti-interference magnetic core', 'Dual output shaft'],
    specs: { 'Voltage': '3V - 6V DC', 'Ratio': '1:48' }
  },
  {
    id: 'mt-6',
    name: 'N20 Gear Motor',
    slug: 'n20-gear-motor',
    sku: 'SKU-MT-06',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Miniature precision metal gearbox DC motor providing high torque in a compact 12mm profile.',
    features: ['All-metal micro spur gearbox', 'D-shaped output shaft', 'Operating voltage 3V-12V'],
    specs: { 'Speed': '100 RPM / 300 RPM', 'Voltage': '6V DC' }
  },
  {
    id: 'mt-7',
    name: 'DC Motor',
    slug: 'dc-toy-motor',
    sku: 'SKU-MT-07',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Standard 130-size hobby DC motor running from 3V to 6V for school projects and fan propellers.',
    features: ['130 form factor', 'High RPM rotation', 'Universal hobby motor'],
    specs: { 'Voltage': '3V - 6V DC', 'RPM': '9000 RPM' }
  },
  {
    id: 'mt-8',
    name: 'Stepper Motor 28BYJ-48',
    slug: 'stepper-motor-28byj-48',
    sku: 'SKU-MT-08',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: '5V 4-phase geared 28BYJ-48 stepper motor bundled with ULN2003 driver board.',
    features: ['5V DC 4-phase stepper motor', 'Includes ULN2003 driver PCB', '1/64 gear reduction ratio'],
    specs: { 'Step Angle': '5.625 x 1/64', 'Voltage': '5V DC' }
  },
  {
    id: 'mt-9',
    name: 'NEMA 17 Stepper Motor',
    slug: 'nema-17-stepper-motor',
    sku: 'SKU-MT-09',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 549,
    originalPrice: 549,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'High torque 1.8-degree bipolar NEMA 17 stepper motor for 3D printers and CNC routers.',
    features: ['4.2 kg-cm holding torque', '1.8 degree step angle', '4-wire bipolar connection'],
    specs: { 'Step Angle': '1.8°', 'Holding Torque': '42 N.cm', 'Rated Current': '1.5A' }
  },
  {
    id: 'mt-10',
    name: 'L298N Motor Driver',
    slug: 'l298n-motor-driver',
    sku: 'SKU-MT-10',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-Bridge power driver module suitable for driving heavy DC gear motors and steppers.',
    features: ['Up to 2A per channel', 'Integrated 5V regulator logic supply', 'Robust terminal blocks'],
    specs: { 'Max Voltage': '35V', 'Peak Current': '2A' }
  },
  {
    id: 'mt-11',
    name: 'L293D Motor Driver',
    slug: 'l293d-motor-driver-shield',
    sku: 'SKU-MT-11',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Arduino Uno motor driver shield capable of driving 4 DC motors or 2 stepper motors simultaneously.',
    features: ['4 H-bridges L293D chipset', '0.6A per bridge', 'Dedicated 2-pin terminal block for external power'],
    specs: { 'Drive Capacity': '4 DC Motors or 2 Steppers', 'Voltage': '4.5V - 25V' }
  },
  {
    id: 'mt-12',
    name: 'DRV8833 Motor Driver',
    slug: 'drv8833-motor-driver',
    sku: 'SKU-MT-12',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Low-voltage dual H-bridge motor driver breakout module with current limiting.',
    features: ['1.5A per channel', 'Over-current protection', 'Low standby current'],
    specs: { 'Voltage': '2.7V - 10.8V', 'Current': '1.5A' }
  },
  {
    id: 'mt-13',
    name: 'TB6612FNG Motor Driver',
    slug: 'tb6612fng-motor-driver',
    sku: 'SKU-MT-13',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Toshiba dual channel MOSFET motor driver offering low heat dissipation.',
    features: ['1.2A continuous current', 'PWM frequency up to 100kHz', 'Decoupling capacitors included'],
    specs: { 'Operating Current': '1.2A', 'Max Peak': '3.2A' }
  },
  {
    id: 'mt-14',
    name: 'A4988 Stepper Driver',
    slug: 'a4988-stepper-driver',
    sku: 'SKU-MT-14',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'Microstepping bipolar stepper motor driver module with translator and aluminum heatsink for 3D printers.',
    features: ['Five step resolutions down to 1/16 microstepping', 'Adjustable current control', 'Thermal shutdown'],
    specs: { 'Max Current': '2A with heatsink', 'Microstep Resolutions': 'Full, 1/2, 1/4, 1/8, 1/16' }
  },
  {
    id: 'mt-15',
    name: 'Motor Wheels',
    slug: 'motor-wheels',
    sku: 'SKU-MT-15',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: '65mm diameter rubber tire with D-hole center hub designed for TT gear motors.',
    features: ['High traction rubber tread', '65mm diameter', 'Center D-shaft coupler'],
    specs: { 'Diameter': '65mm', 'Width': '27mm' }
  },
  {
    id: 'mt-16',
    name: 'Robot Chassis',
    slug: 'robot-chassis-kit',
    sku: 'SKU-MT-16',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Transparent acrylic 2WD smart robot car chassis platform with TT motors, wheels, and caster wheel.',
    features: ['Laser cut acrylic frame', 'Includes 2 TT motors & 65mm wheels', 'Omnidirectional caster wheel'],
    specs: { 'Platform': '2WD', 'Material': 'Acrylic' }
  },
  {
    id: 'mt-17',
    name: 'Motor Couplings',
    slug: 'motor-couplings',
    sku: 'SKU-MT-17',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Solid brass motor shaft coupling connector for linking N20 / DC motor shafts to wheels.',
    features: ['Solid brass alloy', 'Includes grub screws and hex wrench key', 'Precise shaft fit'],
    specs: { 'Shaft Bore': '3mm / 4mm / 5mm' }
  },

  // 6. Power & Battery (22 Items)
  {
    id: 'pb-1',
    name: '18650 Li-Ion Battery',
    slug: '18650-li-ion-battery',
    sku: 'SKU-PB-01',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Standard 3.7V rechargeable 18650 cylindrical lithium-ion cell with 2200mAh capacity for power banks and electronics.',
    features: ['High energy density', '3.7V nominal voltage', 'Rechargeable up to 500 cycles'],
    specs: { 'Capacity': '2200mAh', 'Nominal Voltage': '3.7V', 'Full Charge Voltage': '4.2V' }
  },
  {
    id: 'pb-2',
    name: '3.7V Li-Po Battery',
    slug: '3-7v-lipo-battery',
    sku: 'SKU-PB-02',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Ultra-thin lithium polymer pouch battery cell for embedded wearables and compact microcontrollers.',
    features: ['Flat pouch form factor', 'Integrated PCM protection board', 'JST-PH connector'],
    specs: { 'Voltage': '3.7V', 'Capacity': '500mAh' }
  },
  {
    id: 'pb-3',
    name: '3.7V 750mAh Li-Po',
    slug: '3-7v-750mah-lipo',
    sku: 'SKU-PB-03',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: '3.7V 750mAh high-discharge Li-Po battery pack fitted with protection circuit module.',
    features: ['750mAh power capacity', 'Over-current protection', 'JST connector lead'],
    specs: { 'Capacity': '750mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-4',
    name: '3.7V 1200mAh Li-Po',
    slug: '3-7v-1200mah-lipo',
    sku: 'SKU-PB-04',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Rechargeable 3.7V 1200mAh lithium polymer battery suitable for portable companion devices like GEM.',
    features: ['Long operating runtime', 'High reliability pouch cell', 'Pre-soldered JST leads'],
    specs: { 'Capacity': '1200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-5',
    name: '3.7V 2200mAh Li-Po',
    slug: '3-7v-2200mah-lipo',
    sku: 'SKU-PB-05',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'High capacity 2200mAh 3.7V Li-Po battery pack providing extended power autonomy.',
    features: ['2200mAh heavy duty capacity', 'Integrated short-circuit protection'],
    specs: { 'Capacity': '2200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-6',
    name: '5V USB Power Module',
    slug: '5v-usb-power-module',
    sku: 'SKU-PB-06',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Dual USB 5V 2A power bank motherboard module with charging status digital LED indicators.',
    features: ['Dual 5V 2.1A USB outputs', 'Type-C / Micro-USB input charging', 'Overload & thermal protection'],
    specs: { 'Output': '5V 2.1A', 'Input': '5V 1A' }
  },
  {
    id: 'pb-7',
    name: 'TP4056 Charger Module',
    slug: 'tp4056-charger-module',
    sku: 'SKU-PB-07',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Single-cell 1A lithium battery charging module with Type-C connector and protection IC.',
    features: ['1A charging current', 'Type-C port input', 'Red/Blue status LEDs'],
    specs: { 'Charge Current': '1A', 'Port': 'USB Type-C' }
  },
  {
    id: 'pb-8',
    name: 'TP4050 Charger Module',
    slug: 'tp4050-charger-module',
    sku: 'SKU-PB-08',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'High efficiency linear Li-Ion charger board with thermal foldback protection.',
    features: ['Thermal regulation', 'Programmable charging current', 'Compact PCB footprint'],
    specs: { 'Voltage': '4.5V - 6.5V', 'Current': '1000mA' }
  },
  {
    id: 'pb-9',
    name: '1S BMS Protection Board',
    slug: '1s-bms-protection-board',
    sku: 'SKU-PB-09',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1S 3.7V 3A lithium battery Battery Management System (BMS) protection PCB.',
    features: ['Overcharge cut-off 4.25V', 'Over-discharge cut-off 2.54V', 'Short circuit protection'],
    specs: { 'Series': '1S (3.7V)', 'Max Current': '3A' }
  },
  {
    id: 'pb-10',
    name: '2S BMS Protection Board',
    slug: '2s-bms-protection-board',
    sku: 'SKU-PB-10',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '2S 7.4V 8A BMS protection board for dual 18650 Li-Ion battery pack balancing.',
    features: ['Cell voltage balancing', '8A continuous discharge limit', 'Low heat MOSFETs'],
    specs: { 'Series': '2S (7.4V / 8.4V)', 'Max Current': '8A' }
  },
  {
    id: 'pb-11',
    name: '3S BMS Protection Board',
    slug: '3s-bms-protection-board',
    sku: 'SKU-PB-11',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 190,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '3S 12V 20A Li-Ion battery BMS protection PCB board for power tools and 12V packs.',
    features: ['20A peak load discharge', 'Overcharge, overdischarge & short circuit cutoffs'],
    specs: { 'Series': '3S (11.1V / 12.6V)', 'Current': '20A' }
  },
  {
    id: 'pb-12',
    name: 'Battery Holder 1×18650',
    slug: 'battery-holder-1x18650',
    sku: 'SKU-PB-12',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Single-slot 18650 battery holder case with wire leads for easy breadboard connection.',
    features: ['High quality ABS plastic', 'Pre-stripped red/black wire leads', 'Metal leaf spring contacts'],
    specs: { 'Slots': '1 x 18650 Cell' }
  },
  {
    id: 'pb-13',
    name: 'Battery Holder 2×18650',
    slug: 'battery-holder-2x18650',
    sku: 'SKU-PB-13',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 35,
    originalPrice: 35,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Dual-slot 2x18650 battery holder socket case wired in series for 7.4V power supply.',
    features: ['Holds two 18650 cells', 'Series output wiring', 'M3 mounting holes'],
    specs: { 'Slots': '2 x 18650 Cells' }
  },
  {
    id: 'pb-14',
    name: 'Battery Holder 4×18650',
    slug: 'battery-holder-4x18650',
    sku: 'SKU-PB-14',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 55,
    originalPrice: 55,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Quad-slot 4x18650 battery holder enclosure case for heavy duty 14.8V power packs.',
    features: ['4 slot 18650 enclosure', 'Robust spring contacts', 'Wire leads included'],
    specs: { 'Slots': '4 x 18650 Cells' }
  },
  {
    id: 'pb-15',
    name: 'DC-DC Buck Converter',
    slug: 'dc-dc-buck-converter',
    sku: 'SKU-PB-15',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 adjustable DC-DC step down voltage regulator module providing stable output voltage.',
    features: ['Input up to 35V DC', 'Output adjustable 1.25V-30V', 'High conversion efficiency'],
    specs: { 'Max Current': '3A', 'Efficiency': '92%' }
  },
  {
    id: 'pb-16',
    name: 'DC-DC Boost Converter',
    slug: 'dc-dc-boost-converter',
    sku: 'SKU-PB-16',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 micro 2A DC-DC step up voltage booster board.',
    features: ['Steps 2V up to 28V', 'Compact 36mm x 17mm size', 'Trimmer pot adjustment'],
    specs: { 'Max Current': '2A' }
  },
  {
    id: 'pb-17',
    name: '5V Voltage Regulator',
    slug: '5v-voltage-regulator',
    sku: 'SKU-PB-17',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM7805 TO-220 3-terminal positive 5V 1.5A fixed linear voltage regulator IC.',
    features: ['Fixed 5V output', 'Thermal overload protection', 'Short-circuit current limit'],
    specs: { 'Output Voltage': '5V DC', 'Max Current': '1.5A' }
  },
  {
    id: 'pb-18',
    name: '3.3V Voltage Regulator',
    slug: '3-3v-voltage-regulator',
    sku: 'SKU-PB-18',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'AMS1117-3.3 SOT-223 low dropout (LDO) 3.3V 800mA linear regulator IC module.',
    features: ['Fixed 3.3V LDO output', '800mA output current capability', 'Onboard filter capacitors'],
    specs: { 'Output Voltage': '3.3V DC', 'Max Output Current': '800mA' }
  },
  {
    id: 'pb-19',
    name: 'USB Type-C Power Module',
    slug: 'usb-type-c-power-module',
    sku: 'SKU-PB-19',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'USB Type-C female connector breakout board with DIP pins for 5V power input connection.',
    features: ['Standard Type-C receptacle', 'VBUS, GND, CC1, CC2 breakout pins', 'FR-4 PCB'],
    specs: { 'Interface': 'USB Type-C Female' }
  },
  {
    id: 'pb-[#0066FF]',
    name: 'Rocker / Slide Power Switch',
    slug: 'rocker-slide-power-switch',
    sku: 'SKU-PB-20',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'SPST 2-pin mini ON/OFF power toggle switch for electronic projects.',
    features: ['Snap-in mounting', 'AC 250V 3A / DC 12V 6A rating', 'Tactile latching click'],
    specs: { 'Switch Type': 'SPST ON-OFF' }
  },
  {
    id: 'pb-21',
    name: 'JST Connectors',
    slug: 'jst-connectors-pair',
    sku: 'SKU-PB-21',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 20,
    originalPrice: 20,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'JST-PH 2.0mm 2-pin male and female connector cable pair with 10cm pre-stripped wires.',
    features: ['2.0mm pitch spacing', 'Includes male plug & female socket cable', '22AWG copper wire'],
    specs: { 'Pitch': '2.0mm JST-PH', 'Length': '10cm' }
  },
  {
    id: 'pb-22',
    name: 'DC Barrel Jack',
    slug: 'dc-barrel-jack-socket',
    sku: 'SKU-PB-22',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Standard 5.5mm x 2.1mm DC power female jack socket connector for wall adapter plugs.',
    features: ['5.5x2.1mm standard DC dimensions', 'Panel mount / PCB mount pins', 'Durable metal contacts'],
    specs: { 'Dimensions': '5.5mm x 2.1mm' }
  }
];