export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  categoryName: string;
  subCategory?: string;
  price: number;
  originalPrice: number;
  discountPercent: number;
  inStock: boolean;
  stockCount: number;
  rating: number;
  reviewCount: number;
  image: string;
  gallery?: string[];
  description: string;
  specs: Record<string, string>;
  features: string[];
  isFeatured?: boolean;
}

export interface StoreCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  itemCount: number;
  color: string;
  subCategories: string[];
}

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    id: 'microcontrollers',
    name: 'Microcontrollers',
    slug: 'microcontrollers',
    description: 'High-performance ESP32, Arduino, Raspberry Pi Pico, and AVR microcontroller development boards.',
    icon: 'Cpu',
    itemCount: 12,
    color: 'from-[#0066FF] to-[#2563EB]',
    subCategories: ['ESP32 Series', 'Arduino Boards', 'Raspberry Pi Pico']
  },
  {
    id: 'sensors',
    name: 'Sensors',
    slug: 'sensors',
    description: 'Precision environmental, motion, optical, biometric, gas, and distance sensing modules.',
    icon: 'Wifi',
    itemCount: 19,
    color: 'from-[#0066FF] to-[#0284C7]',
    subCategories: ['Environmental & Gas', 'Motion & Proximity', 'Optical & Sound', 'Biometric']
  },
  {
    id: 'modules',
    name: 'Modules',
    slug: 'modules',
    description: 'Relay drivers, charger controllers, audio amplifiers, wireless transceivers, and RTC modules.',
    icon: 'Layers',
    itemCount: 22,
    color: 'from-blue-600 to-indigo-700',
    subCategories: ['Relays & Drivers', 'Charging & Power', 'Audio & Wireless', 'Timing & Interfaces']
  },
  {
    id: 'displays',
    name: 'Displays',
    slug: 'displays',
    description: 'High-resolution OLED screens, TFT LCD touch displays, 16x2 LCDs, and WS2812B addressable LEDs.',
    icon: 'Monitor',
    itemCount: 13,
    color: 'from-cyan-600 to-blue-700',
    subCategories: ['OLED Displays', 'TFT Displays', 'LCD & Matrix', 'LED Lighting']
  },
  {
    id: 'motors-drivers',
    name: 'Motors & Drivers',
    slug: 'motors-drivers',
    description: 'Precision servos, stepper motors, DC gear motors, motor driver ICs, and robot chassis components.',
    icon: 'Cog',
    itemCount: 17,
    color: 'from-slate-700 to-slate-900',
    subCategories: ['Servo Motors', 'Stepper Motors', 'DC Motors', 'Motor Drivers & Chassis']
  },
  {
    id: 'power-battery',
    name: 'Power & Battery',
    slug: 'power-battery',
    description: 'Li-Ion 18650 cells, Li-Po batteries, BMS protection boards, buck/boost converters, and power connectors.',
    icon: 'BatteryCharging',
    itemCount: 22,
    color: 'from-emerald-600 to-teal-700',
    subCategories: ['Li-Ion & Li-Po', 'BMS & Chargers', 'Voltage Regulators & Holders', 'Connectors & Switches']
  }
];

export const STORE_PRODUCTS: Product[] = [
  // 1. Microcontrollers (12 Items)
  {
    id: 'mc-1',
    name: 'ESP32-WROOM-32',
    slug: 'esp32-wroom-32',
    sku: 'SKU-MC-01',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Dual-core 32-bit Tensilica LX6 microcontroller with integrated 2.4GHz Wi-Fi and Bluetooth v4.2 BR/EDR and BLE.',
    features: ['240 MHz clock speed', '520 KB SRAM', '4MB SPI Flash memory', 'Wi-Fi & BLE integrated'],
    specs: { 'Voltage': '3.3V', 'Processor': 'Dual-Core LX6', 'Flash': '4MB', 'Connectivity': 'Wi-Fi + BLE' }
  },
  {
    id: 'mc-2',
    name: 'ESP32 DevKit V1',
    slug: 'esp32-devkit-v1',
    sku: 'SKU-MC-02',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 120,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Standard 30-pin ESP32 development board with CP2102 USB-to-UART converter and micro-USB port for rapid breadboard prototyping.',
    features: ['30 GPIO Pins', 'Micro-USB interface', 'Onboard EN & Boot switches', 'Dual Core 240MHz'],
    specs: { 'USB Bridge': 'CP2102', 'Pins': '30 GPIO', 'Operating Voltage': '5V via USB / 3.3V Pin' }
  },
  {
    id: 'mc-3',
    name: 'ESP32-C3 SuperMini',
    slug: 'esp32-c3-supermini',
    sku: 'SKU-MC-03',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 80,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Ultra-compact RISC-V 32-bit single-core ESP32-C3 development board featuring USB Type-C and Wi-Fi + BLE 5.0.',
    features: ['RISC-V 32-bit Core @ 160MHz', 'USB Type-C port', 'BLE 5.0 mesh support', 'Ultra small form factor'],
    specs: { 'Core': 'RISC-V 160MHz', 'Bluetooth': 'BLE 5.0', 'Interface': 'USB Type-C' }
  },
  {
    id: 'mc-4',
    name: 'ESP32-C3 Mini',
    slug: 'esp32-c3-mini',
    sku: 'SKU-MC-04',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 189,
    originalPrice: 189,
    discountPercent: 0,
    inStock: true,
    stockCount: 95,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Miniature ESP32-C3 Wi-Fi and Bluetooth board tailored for wearable and space-constrained IoT nodes.',
    features: ['Low power consumption', 'Integrated PCB antenna', 'Type-C USB interface'],
    specs: { 'Architecture': 'RISC-V 32-Bit', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'mc-5',
    name: 'ESP32-S3 DevKit',
    slug: 'esp32-s3-devkit',
    sku: 'SKU-MC-05',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 449,
    originalPrice: 449,
    discountPercent: 0,
    inStock: true,
    stockCount: 60,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Dual-core Xtensa LX7 processor running at 240MHz with vector instructions for AI machine learning edge computation.',
    features: ['Vector acceleration for AI', 'Dual USB Type-C ports', '8MB PSRAM / 8MB Flash'],
    specs: { 'Processor': 'Xtensa Dual-Core LX7', 'PSRAM': '8MB', 'Flash': '8MB' }
  },
  {
    id: 'mc-6',
    name: 'ESP32-CAM',
    slug: 'esp32-cam',
    sku: 'SKU-MC-06',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 399,
    originalPrice: 399,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'ESP32 Wi-Fi + Bluetooth board bundled with an OV2640 2MP camera module and MicroSD card slot for video streaming & surveillance.',
    features: ['OV2640 2MP camera included', 'MicroSD slot up to 4GB', 'Onboard high-brightness LED flash'],
    specs: { 'Camera': 'OV2640 2MP', 'PSRAM': '4MB', 'Storage': 'MicroSD Slot' }
  },
  {
    id: 'mc-7',
    name: 'ESP8266 NodeMCU',
    slug: 'esp8266-nodemcu',
    sku: 'SKU-MC-07',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 219,
    originalPrice: 219,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/microcontroller.svg',
    description: 'Popular open-source Lua-based firmware development board powered by the ESP8266 80MHz Wi-Fi module.',
    features: ['802.11 b/g/n Wi-Fi', 'Integrated micro-USB', '10 GPIO pins with PWM & ADC'],
    specs: { 'Wi-Fi': '2.4GHz', 'Clock Speed': '80MHz', 'Flash': '4MB' }
  },
  {
    id: 'mc-8',
    name: 'Arduino UNO R3',
    slug: 'arduino-uno-r3',
    sku: 'SKU-MC-08',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 399,
    originalPrice: 399,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/arduino.svg',
    description: 'Classic ATmega328P DIP-based microcontroller board with 14 digital I/O pins, 6 analog inputs, and 16MHz crystal.',
    features: ['14 Digital I/O Pins', '6 Analog Inputs', 'DIP socket ATmega328P IC', 'Standard USB Type-B'],
    specs: { 'Microcontroller': 'ATmega328P', 'Clock': '16MHz', 'Operating Voltage': '5V' }
  },
  {
    id: 'mc-9',
    name: 'Arduino Nano',
    slug: 'arduino-nano',
    sku: 'SKU-MC-09',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/arduino.svg',
    description: 'Breadboard-friendly ATmega328P microcontroller board with mini-USB connection.',
    features: ['Compact breadboard layout', '8 Analog Inputs', '14 Digital I/O Pins'],
    specs: { 'Microcontroller': 'ATmega328P', 'Voltage': '5V', 'USB': 'Mini-USB / Type-C' }
  },
  {
    id: 'mc-10',
    name: 'Arduino Mega 2560',
    slug: 'arduino-mega-2560',
    sku: 'SKU-MC-10',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 749,
    originalPrice: 749,
    discountPercent: 0,
    inStock: true,
    stockCount: 75,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/arduino.svg',
    description: 'High pin-count ATmega2560 microcontroller board featuring 54 digital I/O pins and 16 analog inputs for 3D printers and complex robotics.',
    features: ['54 Digital I/O Pins', '16 Analog Inputs', '4 Hardware UART serial ports', '256KB Flash memory'],
    specs: { 'Microcontroller': 'ATmega2560', 'Flash': '256KB', 'SRAM': '8KB' }
  },
  {
    id: 'mc-11',
    name: 'Raspberry Pi Pico',
    slug: 'raspberry-pi-pico',
    sku: 'SKU-MC-11',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Raspberry Pi Pico',
    price: 399,
    originalPrice: 399,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/raspberrypi.svg',
    description: 'Designed by Raspberry Pi, featuring the RP2040 dual-core ARM Cortex-M0+ processor running at 133MHz.',
    features: ['Dual-Core ARM Cortex-M0+ @ 133MHz', '264KB SRAM', '2MB QSPI Flash', 'Programmable I/O (PIO) state machines'],
    specs: { 'SoC': 'RP2040', 'Core': 'Dual ARM Cortex-M0+', 'Flash': '2MB' }
  },
  {
    id: 'mc-12',
    name: 'Raspberry Pi Pico W',
    slug: 'raspberry-pi-pico-w',
    sku: 'SKU-MC-12',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Raspberry Pi Pico',
    price: 549,
    originalPrice: 549,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/raspberrypi.svg',
    description: 'RP2040 microcontroller board enhanced with an onboard Infineon CYW43439 2.4GHz 802.11n wireless chip for IoT connectivity.',
    features: ['Integrated 2.4GHz 802.11n Wi-Fi', 'Bluetooth 5.2 support', 'RP2040 Dual Core processor'],
    specs: { 'Wireless': 'Wi-Fi + BLE', 'Microcontroller': 'RP2040', 'Flash': '2MB' }
  },

  // 2. Sensors (19 Items)
  {
    id: 'sn-1',
    name: 'HC-SR04 Ultrasonic Sensor',
    slug: 'hc-sr04-ultrasonic-sensor',
    sku: 'SKU-SN-01',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/ultrasonic.svg',
    description: 'Non-contact ultrasonic distance measuring module operating from 2cm to 400cm with 3mm precision.',
    features: ['2cm to 400cm range', '5V DC operation', '4-pin interface (VCC, Trig, Echo, GND)'],
    specs: { 'Operating Voltage': '5V DC', 'Ranging Distance': '2cm - 400cm', 'Measuring Angle': '15 degrees' }
  },
  {
    id: 'sn-2',
    name: 'IR Obstacle Sensor',
    slug: 'ir-obstacle-sensor',
    sku: 'SKU-SN-02',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Infrared reflective proximity obstacle detection module with adjustable detection range via onboard potentiometer.',
    features: ['Infrared transmitter & receiver', 'Adjustable sensitivity', 'Digital output pin'],
    specs: { 'Detection Distance': '2cm - 30cm', 'Operating Voltage': '3.3V - 5V' }
  },
  {
    id: 'sn-3',
    name: 'PIR Motion Sensor',
    slug: 'pir-motion-sensor',
    sku: 'SKU-SN-03',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Passive Infrared (PIR) body motion detector module for human intrusion detection and automated lighting.',
    features: ['120 degree cone detection', 'Adjustable delay time & sensitivity', 'Up to 7 meters range'],
    specs: { 'Sensing Range': '3m - 7m', 'Delay Time': '0.3s - 18s' }
  },
  {
    id: 'sn-4',
    name: 'LDR Sensor Module',
    slug: 'ldr-sensor-module',
    sku: 'SKU-SN-04',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Optical & Sound',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Light Dependent Resistor (LDR) photoresistor module with digital and analog outputs for ambient light tracking.',
    features: ['LM393 comparator chip', 'Analog & Digital signal output', 'Adjustable light threshold'],
    specs: { 'Operating Voltage': '3.3V - 5V', 'Output Type': 'DO & AO' }
  },
  {
    id: 'sn-5',
    name: 'DHT11 Temperature & Humidity Sensor',
    slug: 'dht11-sensor',
    sku: 'SKU-SN-05',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Basic composite digital temperature and humidity sensor module with calibrated single-wire digital output.',
    features: ['20-90% RH humidity range', '0-50°C temperature range', '3-pin breakout board'],
    specs: { 'Humidity Accuracy': '±5% RH', 'Temperature Accuracy': '±2°C' }
  },
  {
    id: 'sn-6',
    name: 'DHT22 Temperature & Humidity Sensor',
    slug: 'dht22-sensor',
    sku: 'SKU-SN-06',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'High-precision capacitive humidity and temperature digital sensor module for weather stations.',
    features: ['0-100% RH humidity range', '-40 to 80°C temperature range', '±0.5°C accuracy'],
    specs: { 'Sampling Period': '2 Seconds', 'Operating Voltage': '3.3V - 5.5V' }
  },
  {
    id: 'sn-7',
    name: 'DS18B20 Temperature Sensor',
    slug: 'ds18b20-temperature-sensor',
    sku: 'SKU-SN-07',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Waterproof 1-Wire digital thermometer probe capable of measuring temperatures from -55°C to +125°C.',
    features: ['Waterproof stainless steel tube', '1-Wire interface protocol', '9 to 12-bit selectable resolution'],
    specs: { 'Temperature Range': '-55°C to +125°C', 'Accuracy': '±0.5°C' }
  },
  {
    id: 'sn-8',
    name: 'MQ-2 Gas Sensor',
    slug: 'mq-2-gas-sensor',
    sku: 'SKU-SN-08',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Combustible gas and smoke detector module suitable for detecting LPG, propane, methane, alcohol, and hydrogen.',
    features: ['High sensitivity to LPG and propane', 'Fast response time', 'Analog & Digital outputs'],
    specs: { 'Target Gases': 'LPG, Smoke, Methane', 'Operating Voltage': '5V DC' }
  },
  {
    id: 'sn-9',
    name: 'MQ-135 Air Quality Sensor',
    slug: 'mq-135-air-quality-sensor',
    sku: 'SKU-SN-09',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Air quality hazard sensor module designed for detecting NH3, NOx, alcohol, benzene, smoke, and CO2.',
    features: ['Wide detecting scope', 'Onboard potentiometer for threshold adjust', 'Dual signal output'],
    specs: { 'Target Gases': 'Ammonia, CO2, Smoke', 'Voltage': '5V' }
  },
  {
    id: 'sn-10',
    name: 'Flame Sensor',
    slug: 'flame-sensor',
    sku: 'SKU-SN-10',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Optical & Sound',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Infrared wavelength flame detection module sensitive to fire wavelengths between 760nm to 1100nm.',
    features: ['60-degree detection angle', 'Onboard LM393 comparator', 'Digital & Analog pins'],
    specs: { 'Wavelength Range': '760nm - 1100nm', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'sn-11',
    name: 'Rain Sensor Module',
    slug: 'rain-sensor',
    sku: 'SKU-SN-11',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 190,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Raindrops detection board with nickel-plated weather tracking surface and control driver module.',
    features: ['Nickel plated anti-oxidation board', 'Adjustable sensitivity', 'DO and AO output pins'],
    specs: { 'Board Area': '5cm x 4cm', 'Operating Voltage': '3.3V - 5V' }
  },
  {
    id: 'sn-12',
    name: 'Soil Moisture Sensor',
    slug: 'soil-moisture-sensor',
    sku: 'SKU-SN-12',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 210,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Pronged soil water content detection probe for smart agriculture and automatic plant watering systems.',
    features: ['Two conducting prongs', 'LM393 driver module', 'Digital & Analog outputs'],
    specs: { 'Voltage': '3.3V - 5V', 'Output': 'Digital DO & Analog AO' }
  },
  {
    id: 'sn-13',
    name: 'Sound Sensor Module',
    slug: 'sound-sensor',
    sku: 'SKU-SN-13',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Optical & Sound',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Electret microphone sound intensity detection module for acoustic trigger switches and clapping detectors.',
    features: ['High sensitivity microphone', 'LM393 signal amplifier', 'Adjustable Gain potentiometer'],
    specs: { 'Supply Voltage': '3.3V - 5V', 'Output': 'Digital High/Low' }
  },
  {
    id: 'sn-14',
    name: 'Touch Sensor Module',
    slug: 'touch-sensor',
    sku: 'SKU-SN-14',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 230,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'TTP223 capacitive touch button module providing silent touch-activated digital switching.',
    features: ['TTP223 touch IC', 'Latching or momentary mode toggle', 'Low power idle state'],
    specs: { 'Operating Voltage': '2.0V - 5.5V', 'Response Time': '60ms' }
  },
  {
    id: 'sn-15',
    name: 'Pulse Sensor',
    slug: 'pulse-sensor',
    sku: 'SKU-SN-15',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Biometric',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Plug-and-play optical heart rate sensor module for fingertip pulse telemetry and biometric monitoring.',
    features: ['Optical pulse amplification', 'Noise cancellation circuit', 'Fingertip clip strap included'],
    specs: { 'Operating Voltage': '3V - 5V', 'Output': 'Analog Waveform' }
  },
  {
    id: 'sn-16',
    name: 'MPU6050 Accelerometer & Gyroscope',
    slug: 'mpu6050-gyroscope',
    sku: 'SKU-SN-16',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: '6-DOF MotionTracking device combining a 3-axis gyroscope and 3-axis accelerometer with I2C interface.',
    features: ['Integrated Digital Motion Processor (DMP)', '16-bit ADC converters', 'I2C communication protocol'],
    specs: { 'Gyro Range': '±250 500 1000 2000 °/s', 'Accel Range': '±2 ±4 ±8 ±16g' }
  },
  {
    id: 'sn-17',
    name: 'HC-SR501 PIR Sensor',
    slug: 'hc-sr501-pir-sensor',
    sku: 'SKU-SN-17',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Pyroelectric infrared human motion sensor module featuring automatic trigger control.',
    features: ['Adjustable sensitivity & hold time', 'Repeatable trigger mode', 'Low power drain'],
    specs: { 'Voltage': '4.5V - 20V', 'Sensing Range': 'Up to 7 meters' }
  },
  {
    id: 'sn-18',
    name: 'TCRT5000 Line Sensor',
    slug: 'tcrt5000-line-sensor',
    sku: 'SKU-SN-18',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: 'Reflective optical sensor module for line-following robots and black/white surface discrimination.',
    features: ['Infrared emitter phototransistor', 'LM393 comparator driver', 'Digital & Analog outputs'],
    specs: { 'Sensing Distance': '0.2mm - 15mm', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'sn-19',
    name: 'RFID RC522 Sensor Module',
    slug: 'rfid-rc522-sensor',
    sku: 'SKU-SN-19',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Biometric',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 120,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/sensor.svg',
    description: '13.56MHz SPI RFID reader sensor module bundled with S50 key fob and IC card for access control.',
    features: ['SPI interface protocol', '13.56MHz contactless read/write', 'Includes card and key fob'],
    specs: { 'Frequency': '13.56MHz', 'Operating Current': '13-26mA @ 3.3V' }
  },

  // 3. Modules (22 Items)
  {
    id: 'md-1',
    name: 'RC522 RFID Module',
    slug: 'rc522-rfid-module',
    sku: 'SKU-MD-01',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 100,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'MFRC522 IC based 13.56MHz contactless smart card communication module with SPI bus interface.',
    features: ['High integration reader IC', 'Low voltage 3.3V power', 'Supports Mifare1 S50, S70 cards'],
    specs: { 'Communication': 'SPI', 'Frequency': '13.56 MHz', 'Voltage': '3.3V' }
  },
  {
    id: 'md-2',
    name: 'TP4056 Charging Module',
    slug: 'tp4056-charging-module',
    sku: 'SKU-MD-02',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1A Lithium battery charging module with dual protection IC and Micro-USB / Type-C input.',
    features: ['1A constant current charging', 'Overcharge & over-discharge protection', 'Status indicator LEDs'],
    specs: { 'Charge Current': '1A Adjustable', 'Input Interface': 'USB Type-C' }
  },
  {
    id: 'md-3',
    name: 'TP4050 Charging Module',
    slug: 'tp4050-charging-module',
    sku: 'SKU-MD-03',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Linear Li-Ion battery charger board supporting high current thermal management.',
    features: ['Up to 1A programmable charge rate', 'Soft-start limits inrush current', 'LED status lights'],
    specs: { 'Input Voltage': '4.5V - 6V', 'Max Current': '1000mA' }
  },
  {
    id: 'md-4',
    name: '5V Relay Module',
    slug: '5v-relay-module',
    sku: 'SKU-MD-04',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Standard 5V single channel relay module with optocoupler isolation for switching AC 250V / DC 30V loads.',
    features: ['Optocoupler isolation', 'High current relay AC250V 10A', 'Status LED indicator'],
    specs: { 'Control Voltage': '5V DC', 'Max Load': 'AC 250V 10A / DC 30V 10A' }
  },
  {
    id: 'md-5',
    name: '1-Channel Relay Module',
    slug: '1-channel-relay',
    sku: 'SKU-MD-05',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Single channel isolated relay switch for high voltage appliance control.',
    features: ['NO/NC terminal blocks', 'Low level trigger support'],
    specs: { 'Trigger Current': '5mA', 'Voltage': '5V' }
  },
  {
    id: 'md-6',
    name: '2-Channel Relay Module',
    slug: '2-channel-relay',
    sku: 'SKU-MD-06',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Dual channel 5V relay board for controlling two separate electrical circuits independently.',
    features: ['Dual optocouplers', 'Independent control lines', 'Screw terminal blocks'],
    specs: { 'Channels': '2', 'Max Current': '10A per channel' }
  },
  {
    id: 'md-7',
    name: '4-Channel Relay Module',
    slug: '4-channel-relay',
    sku: 'SKU-MD-07',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 169,
    originalPrice: 169,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Quad channel relay board equipped with optical isolation for home automation systems.',
    features: ['4 independent relays', 'Red LED channel indicators', 'Microcontroller compatible trigger'],
    specs: { 'Channels': '4', 'Rating': '10A 250VAC / 10A 30VDC' }
  },
  {
    id: 'md-8',
    name: 'L298N Motor Driver Module',
    slug: 'l298n-motor-driver-module',
    sku: 'SKU-MD-08',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-bridge motor driver module capable of driving two DC motors or one 4-wire stepper motor.',
    features: ['High power L298N IC', 'Aluminum heatsink onboard', '5V onboard regulator'],
    specs: { 'Motor Supply Voltage': '5V - 35V', 'Peak Current': '2A per bridge' }
  },
  {
    id: 'md-9',
    name: 'DRV8833 Motor Driver Module',
    slug: 'drv8833-motor-driver-module',
    sku: 'SKU-MD-09',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual MOSFET H-bridge motor driver module featuring low power loss for battery-operated mini robots.',
    features: ['Dual H-bridge driver', 'Low RDS(on) MOSFETs', 'Built-in thermal shutdown'],
    specs: { 'Operating Voltage': '2.7V - 10.8V', 'Output Current': '1.5A per channel' }
  },
  {
    id: 'md-10',
    name: 'TB6612FNG Motor Driver Module',
    slug: 'tb6612fng-motor-driver-module',
    sku: 'SKU-MD-10',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'High-efficiency dual DC motor driver module based on Toshiba TB6612FNG MOSFET bridge.',
    features: ['Higher efficiency than L298N', '1.2A continuous current per channel', 'Standby mode for power saving'],
    specs: { 'Supply Voltage': '15V Max', 'Continuous Current': '1.2A per channel' }
  },
  {
    id: 'md-11',
    name: 'MAX98357A I2S Audio Amplifier Module',
    slug: 'max98357a-i2s-amplifier',
    sku: 'SKU-MD-11',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Digital I2S Class-D mono audio amplifier module producing 3.2W output into a 4-ohm speaker for ESP32 sound projects.',
    features: ['Direct digital I2S input', '3.2W Class-D amplifier', 'No external MCLK required'],
    specs: { 'Output Power': '3.2W into 4Ω', 'Operating Voltage': '2.5V - 5.5V' }
  },
  {
    id: 'md-12',
    name: 'MicroSD Card Module',
    slug: 'microsd-card-module',
    sku: 'SKU-MD-12',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'SPI interface MicroSD card reader board with onboard 3.3V level converter for microcontroller data logging.',
    features: ['SPI interface protocol', 'Onboard 3.3V regulator', 'Level shifting buffer IC'],
    specs: { 'Interface': 'SPI', 'Card Supported': 'Micro SD <= 2GB, Micro SDHC <= 32GB' }
  },
  {
    id: 'md-13',
    name: 'Bluetooth HC-05 Module',
    slug: 'bluetooth-hc-05-module',
    sku: 'SKU-MD-13',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Master/Slave SPP (Serial Port Protocol) Bluetooth 2.0 module for wireless serial UART communication.',
    features: ['Master & Slave mode switchable', 'Default baud rate 9600', 'Onboard button for AT commands'],
    specs: { 'Bluetooth Protocol': 'V2.0+EDR', 'Operating Voltage': '3.6V - 6V' }
  },
  {
    id: 'md-14',
    name: 'Bluetooth HC-06 Module',
    slug: 'bluetooth-hc-06-module',
    sku: 'SKU-MD-14',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Slave-only Bluetooth serial transceiver module ideal for smartphone-to-microcontroller wireless control.',
    features: ['Slave mode configuration', 'Simple UART serial interface', 'Signal status LED'],
    specs: { 'Frequency': '2.4GHz ISM', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-15',
    name: 'ESP-NOW-Compatible ESP32 Boards',
    slug: 'esp-now-compatible-esp32',
    sku: 'SKU-MD-15',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'Pre-flashed ESP32 development module configured for ultra-low latency connection-less ESP-NOW protocol peer-to-peer mesh.',
    features: ['Low latency peer-to-peer transmission', 'No router required', 'Pre-tested mesh firmware'],
    specs: { 'Protocol': 'ESP-NOW 2.4GHz', 'Range': 'Up to 200 meters line-of-sight' }
  },
  {
    id: 'md-16',
    name: 'Buzzer Module',
    slug: 'buzzer-module',
    sku: 'SKU-MD-16',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Active/Passive piezo buzzer driver board for audio tone generation and alert beeps.',
    features: ['S8050 transistor drive circuit', 'High sound pressure output', 'Digital pin activation'],
    specs: { 'Operating Voltage': '3.3V - 5V', 'Sound Frequency': '2.5kHz ± 300Hz' }
  },
  {
    id: 'md-17',
    name: 'RTC DS3231 Real-Time Clock Module',
    slug: 'rtc-ds3231-module',
    sku: 'SKU-MD-17',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Extremely accurate I2C real-time clock (RTC) module with integrated TCXO crystal and coin cell backup socket.',
    features: ['Integrated TCXO temperature compensated crystal', 'Battery backup coin cell holder', 'I2C interface with AT24C32 EEPROM'],
    specs: { 'Accuracy': '±2ppm', 'Interface': 'I2C' }
  },
  {
    id: 'md-18',
    name: 'Joystick Module',
    slug: 'joystick-module',
    sku: 'SKU-MD-18',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Dual-axis X/Y analog thumb joystick module with integrated push-button switch.',
    features: ['Two 10k potentiometers for X/Y axes', 'Integrated tactile click button', 'Standard 5-pin header'],
    specs: { 'Output': 'Dual Analog + Digital Push Switch', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-19',
    name: 'Voltage Sensor Module',
    slug: 'voltage-sensor-module',
    sku: 'SKU-MD-19',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Resistive voltage divider module that steps down input DC voltage up to 25V for 5V ADC microcontrollers.',
    features: ['5:1 voltage divider ratio', 'Measures up to 25V DC', 'Screw terminal blocks'],
    specs: { 'Max Input Voltage': '25V DC', 'Divider Ratio': '5:1' }
  },
  {
    id: 'md-20',
    name: 'Current Sensor Module',
    slug: 'current-sensor-module',
    sku: 'SKU-MD-20',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'ACS712 linear Hall-effect current sensor module for measuring AC and DC electrical load current up to 20A.',
    features: ['Hall-effect current sensing', 'Galvanic isolation', 'Low noise analog signal path'],
    specs: { 'Current Range': '20A Max', 'Sensitivity': '100mV/A' }
  },
  {
    id: 'md-21',
    name: 'Step-Down Buck Converter Module',
    slug: 'step-down-buck-converter',
    sku: 'SKU-MD-21',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 DC-DC adjustable step-down buck power module converting high input voltages down to 1.25V-30V.',
    features: ['LM2596 IC switcher', 'Trimmer potentiometer adjustment', 'Up to 3A output capability'],
    specs: { 'Input Voltage': '4V - 35V', 'Output Voltage': '1.23V - 30V' }
  },
  {
    id: 'md-22',
    name: 'Step-Up Boost Converter Module',
    slug: 'boost-converter-module',
    sku: 'SKU-MD-22',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 2A DC-DC step-up voltage boost converter board for stepping battery voltage up to 28V.',
    features: ['High 1.2MHz switching frequency', 'Compact footprint', 'Up to 93% conversion efficiency'],
    specs: { 'Input Voltage': '2V - 24V', 'Max Output Voltage': '28V DC' }
  },

  // 4. Displays (13 Items)
  {
    id: 'dp-1',
    name: '0.96" OLED 128×64 Display',
    slug: '0-96-oled-128x64',
    sku: 'SKU-DP-01',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: 'High-contrast monochrome I2C OLED display module with 128x64 resolution powered by SSD1306 driver chip.',
    features: ['SSD1306 driver controller', 'No backlight needed (self-illuminating)', 'I2C address 0x3C'],
    specs: { 'Resolution': '128x64', 'Interface': 'I2C', 'Color': 'Blue / White / Yellow-Blue' }
  },
  {
    id: 'dp-2',
    name: '1.3" OLED 128×64 Display',
    slug: '1-3-oled-128x64',
    sku: 'SKU-DP-02',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: 'Larger 1.3-inch graphic OLED display module with SH1106 controller and I2C serial interface.',
    features: ['SH1106 driver IC', 'Wide viewing angle > 160 degrees', 'Low power drain'],
    specs: { 'Screen Size': '1.3 Inch', 'Resolution': '128x64', 'Interface': 'I2C' }
  },
  {
    id: 'dp-3',
    name: '1.54" OLED Display',
    slug: '1-54-oled-display',
    sku: 'SKU-DP-03',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 399,
    originalPrice: 399,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/oled.svg',
    description: '1.54-inch full graphic OLED display module with SPI/I2C option for crisp UI dashboards.',
    features: ['SSD1309 controller', '128x64 high contrast display', 'SPI / I2C jumper selectable'],
    specs: { 'Size': '1.54 Inch', 'Driver': 'SSD1309' }
  },
  {
    id: 'dp-4',
    name: '1.8" TFT Display',
    slug: '1-8-tft-display',
    sku: 'SKU-DP-04',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 120,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '128x160 color TFT SPI LCD display module based on ST7735 driver with MicroSD card slot.',
    features: ['18-bit 262,000 full color spectrum', 'SPI bus interface', 'MicroSD slot on back'],
    specs: { 'Resolution': '128x160', 'Driver': 'ST7735', 'Interface': 'SPI' }
  },
  {
    id: 'dp-5',
    name: '2.4" TFT Display',
    slug: '2-4-tft-display',
    sku: 'SKU-DP-05',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 449,
    originalPrice: 449,
    discountPercent: 0,
    inStock: true,
    stockCount: 95,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '240x320 resolution SPI color TFT touchscreen LCD panel powered by ILI9341 controller.',
    features: ['ILI9341 controller IC', '240x320 RGB pixels', 'Resistive touch screen panel'],
    specs: { 'Resolution': '240x320', 'Driver': 'ILI9341' }
  },
  {
    id: 'dp-6',
    name: '2.8" TFT Display',
    slug: '2-8-tft-display',
    sku: 'SKU-DP-06',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 599,
    originalPrice: 599,
    discountPercent: 0,
    inStock: true,
    stockCount: 80,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '2.8-inch Arduino Uno shield format color TFT touchscreen module with SD slot.',
    features: ['Arduino Uno shield form factor', 'Built-in touch panel controller', 'MicroSD storage'],
    specs: { 'Screen Size': '2.8 Inch', 'Interface': '8-bit parallel / SPI' }
  },
  {
    id: 'dp-7',
    name: '3.5" TFT Display',
    slug: '3-5-tft-display',
    sku: 'SKU-DP-07',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 799,
    originalPrice: 799,
    discountPercent: 0,
    inStock: true,
    stockCount: 65,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/tft.svg',
    description: '320x480 pixel high resolution 3.5-inch color TFT touchscreen display panel for ESP32 & Arduino Mega.',
    features: ['320x480 HD resolution', 'ILI9486 driver', 'Full color RGB 65K colors'],
    specs: { 'Resolution': '320x480', 'Driver': 'ILI9486' }
  },
  {
    id: 'dp-8',
    name: '16×2 LCD Display with I2C',
    slug: '16x2-lcd-display',
    sku: 'SKU-DP-08',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/lcd.svg',
    description: 'Blue backlight character 16x2 LCD display pre-soldered with PCF8574 I2C adapter backpack.',
    features: ['Pre-soldered I2C backpack module', 'Contrast trim potentiometer', 'Blue background white text'],
    specs: { 'Characters': '16 Cols x 2 Rows', 'Interface': 'I2C (Address 0x27 / 0x3F)' }
  },
  {
    id: 'dp-9',
    name: '20×4 LCD Display with I2C',
    slug: '20x4-lcd-display',
    sku: 'SKU-DP-09',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/lcd.svg',
    description: 'Large 20 column by 4 row character LCD module bundled with I2C bus backpack converter.',
    features: ['20x4 character matrix', '4-wire I2C interface connection', 'LED backlight switch jumper'],
    specs: { 'Matrix': '20x4 Characters', 'Backlight': 'Blue/Yellow-Green' }
  },
  {
    id: 'dp-10',
    name: '7-Segment LED Display',
    slug: '7-segment-display',
    sku: 'SKU-DP-10',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: '0.56-inch 4-digit 7-segment red LED display module with decimal points for digital clocks and counters.',
    features: ['4 digit multiplexed display', 'High brightness red LEDs', 'Common Cathode / Anode'],
    specs: { 'Digits': '4', 'Color': 'Red' }
  },
  {
    id: 'dp-11',
    name: 'MAX7219 8×8 LED Matrix',
    slug: 'max7219-8x8-led-matrix',
    sku: 'SKU-DP-11',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD & Matrix',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: 'MAX7219 serial input LED driver module connected to an 8x8 dot matrix display for scrolling text.',
    features: ['SPI serial communication', 'Cascadable modular design', 'Individual LED pixel control'],
    specs: { 'Matrix': '8x8 Pixels', 'Driver IC': 'MAX7219' }
  },
  {
    id: 'dp-12',
    name: 'WS2812B LED Strip',
    slug: 'ws2812b-led-strip',
    sku: 'SKU-DP-12',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED Lighting',
    price: 299,
    originalPrice: 299,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: '1-meter 60 LEDs WS2812B addressable RGB LED strip with individual Neopixel pixel control over single wire data pin.',
    features: ['Addressable Neopixel control', '5V DC operation', 'Integrated 5050 RGB LEDs'],
    specs: { 'Density': '60 LEDs/m', 'Voltage': '5V DC', 'Data Protocol': 'Single wire NZR' }
  },
  {
    id: 'dp-13',
    name: 'RGB LED Module',
    slug: 'rgb-led-module',
    sku: 'SKU-DP-13',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED Lighting',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/display.svg',
    description: 'Full color 5050 SMD RGB LED breakout module with current limiting resistors for PWM color mixing.',
    features: ['Red, Green, Blue PWM channels', 'Common Cathode connection', 'Onboard limit resistors'],
    specs: { 'LED Type': '5050 SMD RGB', 'Voltage': '3.3V - 5V' }
  },

  // 5. Motors & Drivers (17 Items)
  {
    id: 'mt-1',
    name: 'SG90 Servo Motor',
    slug: 'sg90-servo-motor',
    sku: 'SKU-MT-01',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: '9g lightweight micro servo motor with 180-degree rotation, plastic gears, and mounting horns.',
    features: ['180 degree rotation angle', '1.8 kg/cm holding torque', 'Includes 3 servo horns'],
    specs: { 'Torque': '1.8 kg-cm @ 4.8V', 'Weight': '9 grams', 'Speed': '0.12 sec/60 deg' }
  },
  {
    id: 'mt-2',
    name: 'MG90S Servo Motor',
    slug: 'mg90s-servo-motor',
    sku: 'SKU-MT-02',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'Micro metal gear 9g servo motor offering increased durability and torque for robotic arms.',
    features: ['Full metal gear train', '2.2 kg/cm torque at 6V', 'Dual ball bearing'],
    specs: { 'Gears': 'Metal', 'Torque': '2.2 kg-cm' }
  },
  {
    id: 'mt-3',
    name: 'MG996R Servo Motor',
    slug: 'mg996r-servo-motor',
    sku: 'SKU-MT-03',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'High-torque standard size digital metal gear servo motor providing up to 11 kg/cm torque.',
    features: ['Metal internal gears', 'Heavy-duty 11 kg/cm torque', 'Double ball bearing shaft'],
    specs: { 'Torque': '11 kg-cm @ 6V', 'Rotation': '180 Degrees' }
  },
  {
    id: 'mt-4',
    name: '8520 Coreless Motor',
    slug: '8520-coreless-motor',
    sku: 'SKU-MT-04',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Ultra-fast 8.5x20mm micro coreless DC motor designed for micro quadcopters and lightweight RC models.',
    features: ['High speed 45,000 RPM @ 3.7V', 'Lightweight coreless design', 'Pre-wired leads'],
    specs: { 'Size': '8.5mm x 20mm', 'Voltage': '3.7V DC', 'Speed': '45000 RPM' }
  },
  {
    id: 'mt-5',
    name: 'TT Gear Motor',
    slug: 'tt-gear-motor',
    sku: 'SKU-MT-05',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual-axis plastic gearbox DC motor for smart robot car chassis with 1:48 gear ratio.',
    features: ['1:48 reduction gear ratio', 'EMC anti-interference magnetic core', 'Dual output shaft'],
    specs: { 'Voltage': '3V - 6V DC', 'Ratio': '1:48' }
  },
  {
    id: 'mt-6',
    name: 'N20 Gear Motor',
    slug: 'n20-gear-motor',
    sku: 'SKU-MT-06',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Miniature precision metal gearbox DC motor providing high torque in a compact 12mm profile.',
    features: ['All-metal micro spur gearbox', 'D-shaped output shaft', 'Operating voltage 3V-12V'],
    specs: { 'Speed': '100 RPM / 300 RPM', 'Voltage': '6V DC' }
  },
  {
    id: 'mt-7',
    name: 'DC Motor',
    slug: 'dc-toy-motor',
    sku: 'SKU-MT-07',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Standard 130-size hobby DC motor running from 3V to 6V for school projects and fan propellers.',
    features: ['130 form factor', 'High RPM rotation', 'Universal hobby motor'],
    specs: { 'Voltage': '3V - 6V DC', 'RPM': '9000 RPM' }
  },
  {
    id: 'mt-8',
    name: 'Stepper Motor 28BYJ-48',
    slug: 'stepper-motor-28byj-48',
    sku: 'SKU-MT-08',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: '5V 4-phase geared 28BYJ-48 stepper motor bundled with ULN2003 driver board.',
    features: ['5V DC 4-phase stepper motor', 'Includes ULN2003 driver PCB', '1/64 gear reduction ratio'],
    specs: { 'Step Angle': '5.625 x 1/64', 'Voltage': '5V DC' }
  },
  {
    id: 'mt-9',
    name: 'NEMA 17 Stepper Motor',
    slug: 'nema-17-stepper-motor',
    sku: 'SKU-MT-09',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 549,
    originalPrice: 549,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'High torque 1.8-degree bipolar NEMA 17 stepper motor for 3D printers and CNC routers.',
    features: ['4.2 kg-cm holding torque', '1.8 degree step angle', '4-wire bipolar connection'],
    specs: { 'Step Angle': '1.8°', 'Holding Torque': '42 N.cm', 'Rated Current': '1.5A' }
  },
  {
    id: 'mt-10',
    name: 'L298N Motor Driver',
    slug: 'l298n-motor-driver',
    sku: 'SKU-MT-10',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-Bridge power driver module suitable for driving heavy DC gear motors and steppers.',
    features: ['Up to 2A per channel', 'Integrated 5V regulator logic supply', 'Robust terminal blocks'],
    specs: { 'Max Voltage': '35V', 'Peak Current': '2A' }
  },
  {
    id: 'mt-11',
    name: 'L293D Motor Driver',
    slug: 'l293d-motor-driver-shield',
    sku: 'SKU-MT-11',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Arduino Uno motor driver shield capable of driving 4 DC motors or 2 stepper motors simultaneously.',
    features: ['4 H-bridges L293D chipset', '0.6A per bridge', 'Dedicated 2-pin terminal block for external power'],
    specs: { 'Drive Capacity': '4 DC Motors or 2 Steppers', 'Voltage': '4.5V - 25V' }
  },
  {
    id: 'mt-12',
    name: 'DRV8833 Motor Driver',
    slug: 'drv8833-motor-driver',
    sku: 'SKU-MT-12',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Low-voltage dual H-bridge motor driver breakout module with current limiting.',
    features: ['1.5A per channel', 'Over-current protection', 'Low standby current'],
    specs: { 'Voltage': '2.7V - 10.8V', 'Current': '1.5A' }
  },
  {
    id: 'mt-13',
    name: 'TB6612FNG Motor Driver',
    slug: 'tb6612fng-motor-driver',
    sku: 'SKU-MT-13',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Toshiba dual channel MOSFET motor driver offering low heat dissipation.',
    features: ['1.2A continuous current', 'PWM frequency up to 100kHz', 'Decoupling capacitors included'],
    specs: { 'Operating Current': '1.2A', 'Max Peak': '3.2A' }
  },
  {
    id: 'mt-14',
    name: 'A4988 Stepper Driver',
    slug: 'a4988-stepper-driver',
    sku: 'SKU-MT-14',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'Microstepping bipolar stepper motor driver module with translator and aluminum heatsink for 3D printers.',
    features: ['Five step resolutions down to 1/16 microstepping', 'Adjustable current control', 'Thermal shutdown'],
    specs: { 'Max Current': '2A with heatsink', 'Microstep Resolutions': 'Full, 1/2, 1/4, 1/8, 1/16' }
  },
  {
    id: 'mt-15',
    name: 'Motor Wheels',
    slug: 'motor-wheels',
    sku: 'SKU-MT-15',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: '65mm diameter rubber tire with D-hole center hub designed for TT gear motors.',
    features: ['High traction rubber tread', '65mm diameter', 'Center D-shaft coupler'],
    specs: { 'Diameter': '65mm', 'Width': '27mm' }
  },
  {
    id: 'mt-16',
    name: 'Robot Chassis',
    slug: 'robot-chassis-kit',
    sku: 'SKU-MT-16',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Transparent acrylic 2WD smart robot car chassis platform with TT motors, wheels, and caster wheel.',
    features: ['Laser cut acrylic frame', 'Includes 2 TT motors & 65mm wheels', 'Omnidirectional caster wheel'],
    specs: { 'Platform': '2WD', 'Material': 'Acrylic' }
  },
  {
    id: 'mt-17',
    name: 'Motor Couplings',
    slug: 'motor-couplings',
    sku: 'SKU-MT-17',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Solid brass motor shaft coupling connector for linking N20 / DC motor shafts to wheels.',
    features: ['Solid brass alloy', 'Includes grub screws and hex wrench key', 'Precise shaft fit'],
    specs: { 'Shaft Bore': '3mm / 4mm / 5mm' }
  },

  // 6. Power & Battery (22 Items)
  {
    id: 'pb-1',
    name: '18650 Li-Ion Battery',
    slug: '18650-li-ion-battery',
    sku: 'SKU-PB-01',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Standard 3.7V rechargeable 18650 cylindrical lithium-ion cell with 2200mAh capacity for power banks and electronics.',
    features: ['High energy density', '3.7V nominal voltage', 'Rechargeable up to 500 cycles'],
    specs: { 'Capacity': '2200mAh', 'Nominal Voltage': '3.7V', 'Full Charge Voltage': '4.2V' }
  },
  {
    id: 'pb-2',
    name: '3.7V Li-Po Battery',
    slug: '3-7v-lipo-battery',
    sku: 'SKU-PB-02',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Ultra-thin lithium polymer pouch battery cell for embedded wearables and compact microcontrollers.',
    features: ['Flat pouch form factor', 'Integrated PCM protection board', 'JST-PH connector'],
    specs: { 'Voltage': '3.7V', 'Capacity': '500mAh' }
  },
  {
    id: 'pb-3',
    name: '3.7V 750mAh Li-Po',
    slug: '3-7v-750mah-lipo',
    sku: 'SKU-PB-03',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: '3.7V 750mAh high-discharge Li-Po battery pack fitted with protection circuit module.',
    features: ['750mAh power capacity', 'Over-current protection', 'JST connector lead'],
    specs: { 'Capacity': '750mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-4',
    name: '3.7V 1200mAh Li-Po',
    slug: '3-7v-1200mah-lipo',
    sku: 'SKU-PB-04',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Rechargeable 3.7V 1200mAh lithium polymer battery suitable for portable companion devices like GEM.',
    features: ['Long operating runtime', 'High reliability pouch cell', 'Pre-soldered JST leads'],
    specs: { 'Capacity': '1200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-5',
    name: '3.7V 2200mAh Li-Po',
    slug: '3-7v-2200mah-lipo',
    sku: 'SKU-PB-05',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'High capacity 2200mAh 3.7V Li-Po battery pack providing extended power autonomy.',
    features: ['2200mAh heavy duty capacity', 'Integrated short-circuit protection'],
    specs: { 'Capacity': '2200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-6',
    name: '5V USB Power Module',
    slug: '5v-usb-power-module',
    sku: 'SKU-PB-06',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Dual USB 5V 2A power bank motherboard module with charging status digital LED indicators.',
    features: ['Dual 5V 2.1A USB outputs', 'Type-C / Micro-USB input charging', 'Overload & thermal protection'],
    specs: { 'Output': '5V 2.1A', 'Input': '5V 1A' }
  },
  {
    id: 'pb-7',
    name: 'TP4056 Charger Module',
    slug: 'tp4056-charger-module',
    sku: 'SKU-PB-07',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Single-cell 1A lithium battery charging module with Type-C connector and protection IC.',
    features: ['1A charging current', 'Type-C port input', 'Red/Blue status LEDs'],
    specs: { 'Charge Current': '1A', 'Port': 'USB Type-C' }
  },
  {
    id: 'pb-8',
    name: 'TP4050 Charger Module',
    slug: 'tp4050-charger-module',
    sku: 'SKU-PB-08',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'High efficiency linear Li-Ion charger board with thermal foldback protection.',
    features: ['Thermal regulation', 'Programmable charging current', 'Compact PCB footprint'],
    specs: { 'Voltage': '4.5V - 6.5V', 'Current': '1000mA' }
  },
  {
    id: 'pb-9',
    name: '1S BMS Protection Board',
    slug: '1s-bms-protection-board',
    sku: 'SKU-PB-09',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1S 3.7V 3A lithium battery Battery Management System (BMS) protection PCB.',
    features: ['Overcharge cut-off 4.25V', 'Over-discharge cut-off 2.54V', 'Short circuit protection'],
    specs: { 'Series': '1S (3.7V)', 'Max Current': '3A' }
  },
  {
    id: 'pb-10',
    name: '2S BMS Protection Board',
    slug: '2s-bms-protection-board',
    sku: 'SKU-PB-10',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '2S 7.4V 8A BMS protection board for dual 18650 Li-Ion battery pack balancing.',
    features: ['Cell voltage balancing', '8A continuous discharge limit', 'Low heat MOSFETs'],
    specs: { 'Series': '2S (7.4V / 8.4V)', 'Max Current': '8A' }
  },
  {
    id: 'pb-11',
    name: '3S BMS Protection Board',
    slug: '3s-bms-protection-board',
    sku: 'SKU-PB-11',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 190,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '3S 12V 20A Li-Ion battery BMS protection PCB board for power tools and 12V packs.',
    features: ['20A peak load discharge', 'Overcharge, overdischarge & short circuit cutoffs'],
    specs: { 'Series': '3S (11.1V / 12.6V)', 'Current': '20A' }
  },
  {
    id: 'pb-12',
    name: 'Battery Holder 1×18650',
    slug: 'battery-holder-1x18650',
    sku: 'SKU-PB-12',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Single-slot 18650 battery holder case with wire leads for easy breadboard connection.',
    features: ['High quality ABS plastic', 'Pre-stripped red/black wire leads', 'Metal leaf spring contacts'],
    specs: { 'Slots': '1 x 18650 Cell' }
  },
  {
    id: 'pb-13',
    name: 'Battery Holder 2×18650',
    slug: 'battery-holder-2x18650',
    sku: 'SKU-PB-13',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 35,
    originalPrice: 35,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Dual-slot 2x18650 battery holder socket case wired in series for 7.4V power supply.',
    features: ['Holds two 18650 cells', 'Series output wiring', 'M3 mounting holes'],
    specs: { 'Slots': '2 x 18650 Cells' }
  },
  {
    id: 'pb-14',
    name: 'Battery Holder 4×18650',
    slug: 'battery-holder-4x18650',
    sku: 'SKU-PB-14',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 55,
    originalPrice: 55,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Quad-slot 4x18650 battery holder enclosure case for heavy duty 14.8V power packs.',
    features: ['4 slot 18650 enclosure', 'Robust spring contacts', 'Wire leads included'],
    specs: { 'Slots': '4 x 18650 Cells' }
  },
  {
    id: 'pb-15',
    name: 'DC-DC Buck Converter',
    slug: 'dc-dc-buck-converter',
    sku: 'SKU-PB-15',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 adjustable DC-DC step down voltage regulator module providing stable output voltage.',
    features: ['Input up to 35V DC', 'Output adjustable 1.25V-30V', 'High conversion efficiency'],
    specs: { 'Max Current': '3A', 'Efficiency': '92%' }
  },
  {
    id: 'pb-16',
    name: 'DC-DC Boost Converter',
    slug: 'dc-dc-boost-converter',
    sku: 'SKU-PB-16',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 micro 2A DC-DC step up voltage booster board.',
    features: ['Steps 2V up to 28V', 'Compact 36mm x 17mm size', 'Trimmer pot adjustment'],
    specs: { 'Max Current': '2A' }
  },
  {
    id: 'pb-17',
    name: '5V Voltage Regulator',
    slug: '5v-voltage-regulator',
    sku: 'SKU-PB-17',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM7805 TO-220 3-terminal positive 5V 1.5A fixed linear voltage regulator IC.',
    features: ['Fixed 5V output', 'Thermal overload protection', 'Short-circuit current limit'],
    specs: { 'Output Voltage': '5V DC', 'Max Current': '1.5A' }
  },
  {
    id: 'pb-18',
    name: '3.3V Voltage Regulator',
    slug: '3-3v-voltage-regulator',
    sku: 'SKU-PB-18',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'AMS1117-3.3 SOT-223 low dropout (LDO) 3.3V 800mA linear regulator IC module.',
    features: ['Fixed 3.3V LDO output', '800mA output current capability', 'Onboard filter capacitors'],
    specs: { 'Output Voltage': '3.3V DC', 'Max Output Current': '800mA' }
  },
  {
    id: 'pb-19',
    name: 'USB Type-C Power Module',
    slug: 'usb-type-c-power-module',
    sku: 'SKU-PB-19',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'USB Type-C female connector breakout board with DIP pins for 5V power input connection.',
    features: ['Standard Type-C receptacle', 'VBUS, GND, CC1, CC2 breakout pins', 'FR-4 PCB'],
    specs: { 'Interface': 'USB Type-C Female' }
  },
  {
    id: 'pb-[#0066FF]',
    name: 'Rocker / Slide Power Switch',
    slug: 'rocker-slide-power-switch',
    sku: 'SKU-PB-20',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'SPST 2-pin mini ON/OFF power toggle switch for electronic projects.',
    features: ['Snap-in mounting', 'AC 250V 3A / DC 12V 6A rating', 'Tactile latching click'],
    specs: { 'Switch Type': 'SPST ON-OFF' }
  },
  {
    id: 'pb-21',
    name: 'JST Connectors',
    slug: 'jst-connectors-pair',
    sku: 'SKU-PB-21',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 20,
    originalPrice: 20,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'JST-PH 2.0mm 2-pin male and female connector cable pair with 10cm pre-stripped wires.',
    features: ['2.0mm pitch spacing', 'Includes male plug & female socket cable', '22AWG copper wire'],
    specs: { 'Pitch': '2.0mm JST-PH', 'Length': '10cm' }
  },
  {
    id: 'pb-22',
    name: 'DC Barrel Jack',
    slug: 'dc-barrel-jack-socket',
    sku: 'SKU-PB-22',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Standard 5.5mm x 2.1mm DC power female jack socket connector for wall adapter plugs.',
    features: ['5.5x2.1mm standard DC dimensions', 'Panel mount / PCB mount pins', 'Durable metal contacts'],
    specs: { 'Dimensions': '5.5mm x 2.1mm' }
  }
];