export interface Product {
  id: string;
  name: string;
  slug: string;
  sku: string;
  categorySlug: string;
  categoryName: string;
  subCategory?: string;
  price: number;
  originalPrice: number;
  discountPercent: number;
  inStock: boolean;
  stockCount: number;
  rating: number;
  reviewCount: number;
  image: string;
  gallery?: string[];
  description: string;
  specs: Record<string, string>;
  features: string[];
  isFeatured?: boolean;
}

export interface StoreCategory {
  id: string;
  name: string;
  slug: string;
  description: string;
  icon: string;
  itemCount: number;
  color: string;
  subCategories: string[];
}

export const STORE_CATEGORIES: StoreCategory[] = [
  {
    id: 'microcontrollers',
    name: 'Microcontrollers',
    slug: 'microcontrollers',
    description: 'High-performance ESP32, ESP8266, and Arduino microcontroller development boards and modules.',
    icon: 'Cpu',
    itemCount: 7,
    color: 'from-[#0066FF] to-[#2563EB]',
    subCategories: ['ESP32 Series', 'Arduino Boards']
  },
  {
    id: 'sensors',
    name: 'Sensors',
    slug: 'sensors',
    description: 'Precision environmental, motion, optical, biometric, gas, and distance sensing modules.',
    icon: 'Wifi',
    itemCount: 10,
    color: 'from-[#0066FF] to-[#0284C7]',
    subCategories: ['Environmental & Gas', 'Motion & Proximity', 'Optical & Sound', 'Biometric']
  },
  {
    id: 'modules',
    name: 'Modules',
    slug: 'modules',
    description: 'Relay drivers, charger controllers, audio amplifiers, wireless transceivers, and RTC modules.',
    icon: 'Layers',
    itemCount: 22,
    color: 'from-blue-600 to-indigo-700',
    subCategories: ['Relays & Drivers', 'Charging & Power', 'Audio & Wireless', 'Timing & Interfaces']
  },
  {
    id: 'displays',
    name: 'Displays',
    slug: 'displays',
    description: 'High-resolution OLED screens, TFT LCD touch displays, 16x2 LCDs, and WS2812B addressable LEDs.',
    icon: 'Monitor',
    itemCount: 10,
    color: 'from-cyan-600 to-blue-700',
    subCategories: ['OLED Displays', 'TFT Displays', 'LCD Displays', 'LED & Matrix']
  },
  {
    id: 'motors-drivers',
    name: 'Motors & Drivers',
    slug: 'motors-drivers',
    description: 'Precision servos, stepper motors, DC gear motors, motor driver ICs, and robot chassis components.',
    icon: 'Cog',
    itemCount: 17,
    color: 'from-slate-700 to-slate-900',
    subCategories: ['Servo Motors', 'Stepper Motors', 'DC Motors', 'Motor Drivers & Chassis']
  },
  {
    id: 'power-battery',
    name: 'Power & Battery',
    slug: 'power-battery',
    description: 'Li-Ion 18650 cells, Li-Po batteries, BMS protection boards, buck/boost converters, and power connectors.',
    icon: 'BatteryCharging',
    itemCount: 22,
    color: 'from-emerald-600 to-teal-700',
    subCategories: ['Li-Ion & Li-Po', 'BMS & Chargers', 'Voltage Regulators & Holders', 'Connectors & Switches']
  }
];

export const STORE_PRODUCTS: Product[] = [
  // 1. ESP32-WROOM-32
  {
    id: 'mc-1',
    name: 'ESP32-WROOM-32',
    slug: 'esp32-wroom-32',
    sku: 'SKU-MC-01',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248395/awie_store/microcontrollers/esp32-wroom-32-module/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248395/awie_store/microcontrollers/esp32-wroom-32-module/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248396/awie_store/microcontrollers/esp32-wroom-32-module/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248394/awie_store/microcontrollers/esp32-wroom-32-module/gpio-view.jpg'
    ],
    description: 'ESP32-WROOM-32 is a powerful, general-purpose Wi-Fi + Bluetooth + BLE MCU module by Espressif. Powered by the ESP32-D0WDQ6 dual-core 32-bit Tensilica Xtensa LX6 processor operating at up to 240 MHz, it integrates 4 MB SPI flash, an onboard PCB antenna, and rich peripheral interfaces. Note: Espressif marks original ESP32-WROOM-32 as NRND (Not Recommended for New Designs); recommended for existing production or replacement needs.',
    features: [
      'Dual-core 32-bit Tensilica Xtensa LX6 processor @ up to 240 MHz',
      '448 KB ROM, 520 KB SRAM, 4 MB integrated SPI Flash',
      '802.11 b/g/n Wi-Fi (2.4 GHz, up to 150 Mbps)',
      'Bluetooth v4.2 BR/EDR & BLE (Bluetooth Low Energy)',
      'Up to 32 configurable GPIO pins',
      'Rich peripherals: 12-bit ADC (18 ch), 2x 8-bit DAC, 3x UART, 3x SPI, 2x I2C, 2x I2S, 16x PWM, TWAI (CAN 2.0)',
      '10x Capacitive Touch sensor channels',
      'Operating Voltage: 3.0 V – 3.6 V (3.3 V Typical)',
      'Ultra-compact module dimensions: 18.00 × 25.50 × 3.10 mm',
      'Integrated PCB trace antenna'
    ],
    specs: {
      'MCU Core': 'ESP32-D0WDQ6 (Dual-Core Xtensa LX6)',
      'Clock Speed': '80 MHz to 240 MHz',
      'Internal SRAM': '520 KB',
      'ROM': '448 KB',
      'Flash Memory': '4 MB SPI Flash',
      'Wi-Fi Standard': '802.11 b/g/n (2.4 GHz)',
      'Bluetooth': 'v4.2 BR/EDR & BLE',
      'GPIO Count': 'Up to 32 Pins',
      'Analog Peripherals': '12-bit ADC (18 Channels), 2x 8-bit DAC',
      'Digital Interfaces': '3x UART, 3x SPI, 2x I2C, 2x I2S, 16x PWM, TWAI (CAN 2.0)',
      'Touch Sensing': '10 Capacitive Touch Pins',
      'Operating Voltage': '3.0 V – 3.6 V (3.3 V Nom.)',
      'Operating Current': '80 mA Average (Deep Sleep < 10 µA)',
      'Module Dimensions': '18.00 × 25.50 × 3.10 mm',
      'Lifecycle Status': 'NRND (Espressif Official)'
    },
    isFeatured: true
  },

  // 2. ESP32-C3 SuperMini
  {
    id: 'mc-3',
    name: 'ESP32-C3 SuperMini',
    slug: 'esp32-c3-supermini',
    sku: 'SKU-MC-03',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248398/awie_store/microcontrollers/esp32-c3-supermini/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248398/awie_store/microcontrollers/esp32-c3-supermini/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248399/awie_store/microcontrollers/esp32-c3-supermini/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248397/awie_store/microcontrollers/esp32-c3-supermini/gpio-view.jpg'
    ],
    description: 'ESP32-C3 SuperMini is an ultra-compact RISC-V 32-bit single-core development board equipped with native USB Type-C, Wi-Fi 4, and Bluetooth 5.0 LE. Operating at up to 160 MHz, its miniature 22.5 × 18 mm footprint with castellated holes makes it ideal for space-constrained wearables and smart IoT nodes.',
    features: [
      '32-bit RISC-V single-core processor up to 160 MHz',
      '400 KB SRAM, 384 KB ROM, 4 MB integrated SPI Flash',
      '2.4 GHz Wi-Fi 802.11 b/g/n & Bluetooth 5 (LE) / Mesh support',
      'Native USB Type-C interface for CDC/JTAG debugging and power',
      '11x Digital GPIOs, 4x ADC channels, 1x SPI, 1x I2C, 1x UART, PWM on all pins',
      'Castellated holes for SMD surface mounting or pin header usage',
      'Ultra-compact form factor (22.5 × 18.0 mm)'
    ],
    specs: {
      'MCU Architecture': '32-bit RISC-V Single-Core (ESP32-C3)',
      'Clock Speed': 'Up to 160 MHz',
      'SRAM / ROM': '400 KB SRAM / 384 KB ROM',
      'Flash Memory': '4 MB SPI Flash',
      'Wi-Fi': '2.4 GHz 802.11 b/g/n (150 Mbps)',
      'Bluetooth': 'Bluetooth 5.0 LE & Mesh',
      'USB Port': 'Native USB Type-C (Serial / JTAG)',
      'GPIO Count': '11 Digital GPIOs',
      'Analog Inputs': '4-Channel 12-bit ADC',
      'Operating Voltage': '3.3 V Logic (5 V Input via USB/VIN)',
      'Dimensions': '22.5 × 18.0 × 4.5 mm'
    }
  },

  // 5. ESP32-S3 DevKit
  {
    id: 'mc-5',
    name: 'ESP32-S3 DevKit',
    slug: 'esp32-s3-devkit',
    sku: 'SKU-MC-05',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248404/awie_store/microcontrollers/esp32-s3-devkit/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248404/awie_store/microcontrollers/esp32-s3-devkit/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248405/awie_store/microcontrollers/esp32-s3-devkit/top-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248403/awie_store/microcontrollers/esp32-s3-devkit/gpio-view.jpg'
    ],
    description: 'ESP32-S3 DevKit is an advanced development board powered by Espressif’s dual-core Xtensa LX7 processor with vector instructions for AI/ML edge computing (TinyML, speech recognition, face detection). Features dual USB ports (Native USB OTG + UART), 8 MB Flash, and Bluetooth 5 LE.',
    features: [
      'Dual-Core Xtensa LX7 32-bit CPU running up to 240 MHz',
      'Vector expansion instructions for hardware AI / ML acceleration',
      '512 KB SRAM, 384 KB ROM, 8 MB SPI Flash (with optional PSRAM support)',
      '2.4 GHz Wi-Fi 802.11 b/g/n & Bluetooth 5 (LE) with Long Range support',
      'Dual USB ports: 1x Native USB 1.1 OTG + 1x USB-to-UART Bridge',
      'Up to 45 GPIO pins with 14 Capacitive Touch channels & 20 ADC channels',
      'Interfaces: SPI, I2C, I2S, UART, PWM, SD/MMC, TWAI (CAN 2.0)'
    ],
    specs: {
      'CPU': 'Dual-Core Xtensa LX7 (240 MHz)',
      'AI Accelerator': 'Vector Instructions for Neural Networks',
      'SRAM / Flash': '512 KB SRAM / 8 MB SPI Flash',
      'Wi-Fi': '2.4 GHz 802.11 b/g/n',
      'Bluetooth': 'Bluetooth 5.0 LE & Long Range',
      'USB Interface': 'Dual USB (Native USB OTG + UART Bridge)',
      'GPIO Count': 'Up to 45 GPIO Pins',
      'Touch Sensing': '14 Touch Capacitive Pins',
      'ADC Inputs': '20 Channels (12-bit)',
      'Board Size': '62.0 × 28.0 × 13.0 mm'
    }
  },

  // 6. ESP32-CAM
  {
    id: 'mc-6',
    name: 'ESP32-CAM Vision & Wi-Fi Board',
    slug: 'esp32-cam',
    sku: 'SKU-MC-06',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248401/awie_store/microcontrollers/esp32-cam/side-viwe.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248401/awie_store/microcontrollers/esp32-cam/side-viwe.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248402/awie_store/microcontrollers/esp32-cam/top-view.webp',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248400/awie_store/microcontrollers/esp32-cam/gpio-view.png'
    ],
    description: 'ESP32-CAM is a compact development board featuring an ESP32 MCU, 4 MB external PSRAM, an onboard MicroSD slot, an ultra-bright White LED flash, and an OV2640 2 MP camera module. Perfect for wireless video streaming, AI face recognition, face tracking, and IoT surveillance.',
    features: [
      'Dual-Core ESP32 processor up to 240 MHz with Wi-Fi & BLE',
      'Includes OV2640 2 Megapixel camera module (UXGA 1600 × 1200 resolution)',
      '4 MB External IPUS PSRAM for high-resolution JPEG frame buffering',
      'Onboard MicroSD card socket (supports up to 4 GB SPI mode storage)',
      'Ultra-bright onboard White LED Flashlight (GPIO4 controlled)',
      'Supports JPEG, BMP, and Grayscale image capture formats',
      'Low power sleep modes down to 6 mA in deep sleep'
    ],
    specs: {
      'MCU': 'ESP32 Dual-Core @ 240 MHz',
      'Camera Sensor': 'OV2640 (2 Megapixel included)',
      'Max Resolution': '1600 × 1200 (UXGA)',
      'PSRAM': '4 MB External PSRAM',
      'Storage': 'MicroSD Slot (Up to 4 GB)',
      'Wi-Fi / BT': '2.4 GHz 802.11 b/g/n + Bluetooth 4.2 BLE',
      'Flash LED': 'Ultra-bright White LED (GPIO4)',
      'Power Supply': '5 V DC / 2 A Recommended',
      'Dimensions': '27.0 × 40.5 × 4.5 mm'
    }
  },

  // 7. ESP8266 NodeMCU
  {
    id: 'mc-7',
    name: 'ESP8266 NodeMCU V2',
    slug: 'esp8266-nodemcu',
    sku: 'SKU-MC-07',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'ESP32 Series',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248407/awie_store/microcontrollers/esp8266-nodemcu/top-view.webp',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248405/awie_store/microcontrollers/esp8266-nodemcu/gpio-view.webp'
    ],
    description: 'ESP8266 NodeMCU V2 is an open-source Wi-Fi development board built around the ESP8266EX SoC. Featuring 4 MB SPI flash, an onboard CP2102/CH340 USB-to-UART bridge, and 10 GPIO pins, it provides an affordable entry into Wi-Fi IoT projects, Home Assistant integration, and Arduino IDE programming.',
    features: [
      'Tensilica Xtensa 32-bit single-core L106 processor @ 80 / 160 MHz',
      'Integrated 802.11 b/g/n Wi-Fi transceiver (2.4 GHz, WPA/WPA2)',
      '4 MB SPI Flash memory (Winbond 25Q32)',
      'Onboard USB-to-UART converter for plug-and-play programming',
      '17x GPIO pins (10x PWM enabled, SPI, I2C, UART support)',
      '1x 10-bit ADC channel (0 – 3.3V via onboard divider)',
      'Breadboard-friendly 30-pin form factor'
    ],
    specs: {
      'SoC': 'ESP8266EX (32-Bit @ 80/160 MHz)',
      'Flash Memory': '4 MB SPI Flash',
      'SRAM': '64 KB Instruction / 96 KB Data',
      'Wi-Fi Standard': '2.4 GHz 802.11 b/g/n',
      'USB Interface': 'CP2102 / CH340 Bridge',
      'Digital I/O': '17 Pins (10 PWM)',
      'Analog Input': '1 Channel (10-bit ADC)',
      'Operating Voltage': '3.3 V Logic (5 V USB/VIN)',
      'Dimensions': '48.0 × 25.0 × 13.0 mm'
    }
  },

  // 8. Arduino UNO R3 Compatible
  {
    id: 'mc-8',
    name: 'Arduino UNO R3 Compatible Board',
    slug: 'arduino-uno-r3',
    sku: 'SKU-MC-08',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-uno-r3/top-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-uno-r3/top-view.jpg'
    ],
    description: 'Arduino UNO R3 Compatible Development Board based on the Microchip ATmega328P 8-bit AVR microcontroller. Featuring 14 digital I/O pins, 6 analog inputs, a 16 MHz crystal oscillator, USB Type-B port, and DC barrel jack, this board is the gold standard for electronics learning, robotics, and prototyping.',
    features: [
      'ATmega328P 8-bit AVR RISC microcontroller operating at 16 MHz',
      '14 Digital Input/Output pins (6 PWM outputs: D3, D5, D6, D9, D10, D11)',
      '6 Analog Input channels (A0 to A5 with 10-bit ADC resolution)',
      '32 KB Flash memory (0.5 KB used by Optiboot bootloader), 2 KB SRAM, 1 KB EEPROM',
      '5 V DC operating logic level',
      'CH340G / ATmega16U2 USB interface for seamless PC communication',
      'DC Barrel Jack input supporting 7–12 V DC power supply'
    ],
    specs: {
      'Microcontroller': 'ATmega328P (8-Bit AVR)',
      'Clock Speed': '16 MHz Crystal',
      'Flash Memory': '32 KB (0.5 KB Bootloader)',
      'SRAM / EEPROM': '2 KB SRAM / 1 KB EEPROM',
      'Digital I/O Pins': '14 (6 PWM Channels)',
      'Analog Inputs': '6 Channels (10-bit ADC)',
      'Operating Voltage': '5 V DC Logic',
      'Input Voltage (Recommended)': '7 V – 12 V DC (Barrel Jack / VIN)',
      'USB Connector': 'USB Type-B Standard',
      'Board Dimensions': '68.6 × 53.4 mm'
    }
  },

  // 9. Arduino Nano R3 Compatible
  {
    id: 'mc-9',
    name: 'Arduino Nano R3 Compatible Board',
    slug: 'arduino-nano',
    sku: 'SKU-MC-09',
    categorySlug: 'microcontrollers',
    categoryName: 'Microcontrollers',
    subCategory: 'Arduino Boards',
    price: 0,
    originalPrice: 0,
    discountPercent: 0,
    inStock: true,
    stockCount: 0,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248391/awie_store/microcontrollers/arduino-nano-r3/side-view.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248391/awie_store/microcontrollers/arduino-nano-r3/side-view.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788248393/awie_store/microcontrollers/arduino-nano-r3/top-view.jpg'
    ],
    description: 'Arduino Nano R3 Compatible is a compact, breadboard-friendly development board based on the ATmega328P microcontroller. Offering 22 I/O pins (including 8 analog inputs) in a tiny 45 × 18 mm layout, it provides full UNO functionality in a miniature footprint.',
    features: [
      'ATmega328P 8-bit AVR RISC processor @ 16 MHz',
      'Breadboard-friendly 30-pin dual inline package layout',
      '14 Digital I/O pins (6 PWM channels)',
      '8 Analog Input channels (A0 to A7, 10-bit ADC resolution)',
      '32 KB Flash memory, 2 KB SRAM, 1 KB EEPROM',
      '5 V DC operating logic level',
      'Mini-USB / USB Type-C connector with CH340G USB interface'
    ],
    specs: {
      'Microcontroller': 'ATmega328P (8-Bit AVR)',
      'Clock Speed': '16 MHz',
      'Flash Memory': '32 KB (2 KB Bootloader)',
      'SRAM / EEPROM': '2 KB SRAM / 1 KB EEPROM',
      'Digital I/O': '14 Pins (6 PWM)',
      'Analog Inputs': '8 Channels (10-bit ADC)',
      'Logic Voltage': '5 V DC',
      'Input Voltage (VIN)': '7 V – 12 V DC',
      'USB Connector': 'Mini-USB / USB Type-C',
      'Board Dimensions': '45.0 × 18.0 mm (Weight ~7 g)'
    }
  },

  // 2. Sensors (10 Items)
  {
    id: 'sn-1',
    name: 'HC-SR04 Ultrasonic Distance Sensor',
    slug: 'hc-sr04-ultrasonic-sensor',
    sku: 'SKU-SN-01',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256080/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256080/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/hc-sr04-ultrasonic-distance-sensor_back-jpg.jpg'
    ],
    description: 'HC-SR04 is an ultrasonic distance-measuring module designed for obstacle detection, distance measurement and robotics applications.',
    features: [
      '2cm to 400cm typical measuring range with 3mm precision',
      '5 V DC operation at 40 kHz frequency',
      '4-pin interface (VCC, Trig, Echo, GND)',
      'Ideal for robot obstacle avoidance, distance measurement, and parking prototypes'
    ],
    specs: {
      'Sensor Type': 'Ultrasonic',
      'Operating Voltage': '5 V DC',
      'Frequency': '40 kHz',
      'Typical Measuring Range': '2–400 cm',
      'Interface': 'VCC, Trig, Echo, GND',
      'Output': 'Echo pulse',
      'Board Width': '40 mm',
      'Board Height': '20 mm',
      'Side Height': '15 mm'
    }
  },
  {
    id: 'sn-2',
    name: 'Infrared IR Obstacle Avoidance Sensor Module',
    slug: 'ir-obstacle-sensor',
    sku: 'SKU-SN-02',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_top-view-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_top-view-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256084/awie_store/sensors/ir-obstacle-avoidance-sensor-module_side-view-jpg.jpg'
    ],
    description: 'An infrared obstacle-detection module that detects nearby objects using reflected infrared light and provides a digital output.',
    features: [
      'Infrared reflective proximity sensor with 2–30 cm detection range',
      '35° detection angle with onboard sensitivity potentiometer adjustment',
      'LM393 voltage comparator with active low digital output',
      'Includes mounting screw holes for line-following robots and proximity automation'
    ],
    specs: {
      'Sensor Type': 'Infrared reflective',
      'Detection Range': '2–30 cm',
      'Detection Angle': '35°',
      'Comparator': 'LM393',
      'Output': 'Digital',
      'Output Logic': 'Active Low',
      'Adjustment': 'Sensitivity adjustable',
      'Mounting': 'Screw holes'
    }
  },
  {
    id: 'sn-3',
    name: 'HC-SR501 PIR Motion Sensor',
    slug: 'pir-motion-sensor',
    sku: 'SKU-SN-03',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256082/awie_store/sensors/hc-sr501-pir-motion-sensor_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256082/awie_store/sensors/hc-sr501-pir-motion-sensor_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256081/awie_store/sensors/hc-sr501-pir-motion-sensor_back-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256083/awie_store/sensors/hc-sr501-pir-motion-sensor_gpio-info-jpg.jpg'
    ],
    description: 'HC-SR501 is a passive infrared motion sensor module designed to detect movement of people and other warm objects.',
    features: [
      '3–7 m adjustable detection distance with <140° detection angle',
      'Ultra-low current drain (<60 µA) with 4.5–20 V DC wide supply voltage',
      '2.5 s default blockade/delay time',
      'Operating temperature range from −20°C to +80°C'
    ],
    specs: {
      'Sensor Type': 'PIR',
      'Operating Voltage': '4.5–20 V DC',
      'Current Drain': '<60 µA',
      'Detection Distance': '3–7 m, adjustable',
      'Detection Angle': '<140°',
      'Default Blockade/Delay': '2.5 s',
      'Operating Temperature': '−20°C to +80°C',
      'Output': 'Digital motion signal'
    }
  },
  {
    id: 'sn-4',
    name: 'LDR Light Sensor Module — LM393',
    slug: 'ldr-sensor-module',
    sku: 'SKU-SN-04',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Optical & Sound',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256085/awie_store/sensors/ldr-light-sensor-module_front-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256085/awie_store/sensors/ldr-light-sensor-module_front-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256086/awie_store/sensors/ldr-light-sensor-module_top-info-jpg.jpg'
    ],
    description: 'An LDR-based light sensor module for detecting ambient light intensity. It provides both analog and digital outputs and includes adjustable sensitivity.',
    features: [
      'Photoresistor / LDR sensor element with LM393 voltage comparator',
      '3.3–5 V DC operating range with dual Digital (DO) & Analog (AO) output pins',
      'Adjustable sensitivity potentiometer for setting light detection threshold',
      'Compact 33 × 14 × 8 mm footprint (4 g weight) for smart lamps and ambient light automation'
    ],
    specs: {
      'Sensor': 'LDR / Photoresistor',
      'Comparator': 'LM393',
      'Operating Voltage': '3.3–5 V',
      'Digital Output': 'DO',
      'Analog Output': 'AO',
      'Sensitivity': 'Adjustable potentiometer',
      'Length': '33 mm',
      'Width': '14 mm',
      'Height': '8 mm',
      'Weight': '4 g'
    }
  },
  {
    id: 'sn-5',
    name: 'DHT11 Digital Temperature & Humidity Sensor',
    slug: 'dht11-sensor',
    sku: 'SKU-SN-05',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht11-temperature-humidity-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht11-temperature-humidity-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256074/awie_store/sensors/dht11-temperature-humidity-sensor_side-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256074/awie_store/sensors/dht11-temperature-humidity-sensor_gpio-jpg.jpg'
    ],
    description: 'DHT11 is a low-cost digital sensor for measuring ambient temperature and relative humidity.',
    features: [
      '0–50°C temperature range (±2°C accuracy)',
      '20–90% RH relative humidity range (±5% RH accuracy)',
      '16-bit digital output with 1 Hz sampling rate',
      '3–5 V supply with single-wire digital interface'
    ],
    specs: {
      'Sensor Type': 'Digital temperature + humidity',
      'Supply': '3–5 V',
      'Temperature Range': '0–50°C',
      'Temperature Accuracy': '±2°C',
      'Humidity Range': '20–90% RH',
      'Humidity Accuracy': '±5% RH',
      'Resolution': '16-bit digital output',
      'Sampling': 'Up to 1 Hz',
      'Interface': 'Single-wire digital'
    }
  },
  {
    id: 'sn-6',
    name: 'DHT22 / AM2302 Digital Temperature & Humidity Sensor',
    slug: 'dht22-sensor',
    sku: 'SKU-SN-06',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256077/awie_store/sensors/dht22-am2302-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256077/awie_store/sensors/dht22-am2302-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256076/awie_store/sensors/dht22-am2302-sensor_back-jpg.jpg'
    ],
    description: 'DHT22 is a digital temperature and humidity sensor offering higher measurement range and accuracy than the basic DHT11.',
    features: [
      '−40 to +80°C temperature range with ±0.5°C accuracy',
      '0–99.9% RH humidity range with ±2% RH accuracy',
      'High 0.1°C / 0.1% RH resolution',
      'Calibrated single-wire digital output for HVAC and weather station prototypes'
    ],
    specs: {
      'Sensor Type': 'Digital temperature + humidity',
      'Model': 'DHT22 / AM2302',
      'Temperature Range': '−40 to +80°C',
      'Humidity Range': '0–99.9% RH',
      'Temperature Accuracy': '±0.5°C',
      'Humidity Accuracy': '±2% RH around 10–90% RH',
      'Temperature Resolution': '0.1°C',
      'Humidity Resolution': '0.1% RH',
      'Output': 'Calibrated digital signal',
      'Interface': 'Single-wire digital'
    }
  },
  {
    id: 'sn-7',
    name: 'DS18B20 Waterproof Temperature Sensor Probe',
    slug: 'ds18b20-temperature-sensor',
    sku: 'SKU-SN-07',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/ds18b20-temperature-sensor-prob_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256079/awie_store/sensors/ds18b20-temperature-sensor-prob_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256078/awie_store/sensors/ds18b20-temperature-sensor-prob_gipo-info-jpg.jpg'
    ],
    description: 'Waterproof digital temperature sensor probe with a stainless-steel housing and 1-Wire interface, suitable for liquid, outdoor, IoT and embedded temperature monitoring.',
    features: [
      'Waterproof stainless-steel probe (approx. 6 mm × 45–50 mm) with sealed housing',
      '1-Wire interface — only one data pin required, supports multi-sensor bus',
      '−55°C to +125°C range with ±0.5°C accuracy, 9–12-bit programmable resolution',
      'Long ~1 m 3-wire cable — suitable for aquarium, soil, liquid, and outdoor environments'
    ],
    specs: {
      'Sensor IC': 'DS18B20',
      'Sensor Type': 'Digital temperature sensor',
      'Interface': '1-Wire',
      'Operating Voltage': '3.0–5.5 V',
      'Temperature Range': '−55°C to +125°C',
      'Accuracy': '±0.5°C from −10°C to +85°C',
      'Resolution': '9-bit to 12-bit programmable',
      'Probe Material': 'Stainless steel',
      'Probe Diameter': 'Approx. 6 mm',
      'Probe Length': 'Approx. 45–50 mm',
      'Cable Length': 'Approx. 1 metre',
      'Cable': '3-wire (Red=VCC, Black=GND, Yellow/White=DATA)',
      'Waterproof': 'Yes — sealed probe',
      'Pull-up resistor': '4.7 kΩ recommended',
      'Conversion Time': 'Up to 750 ms at 12-bit',
      'Unique ID': '64-bit'
    }
  },
  {
    id: 'sn-8',
    name: 'MQ-2 Smoke, LPG & Gas Sensor Module',
    slug: 'mq-2-gas-sensor',
    sku: 'SKU-SN-08',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Environmental & Gas',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256089/awie_store/sensors/mq-2-gas-sensor-module_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256089/awie_store/sensors/mq-2-gas-sensor-module_top-jpg.jpg'
    ],
    description: 'MQ-2 is a gas-sensing module commonly used in electronics projects for detecting smoke and several combustible gases.',
    features: [
      'Detects smoke, LPG, butane, hydrogen, and combustible gas concentrations',
      'Dual signal outputs: 0–5 V Analog + TTL Digital',
      'Onboard potentiometer sensitivity threshold adjustment',
      'Compact 36 × 20 × 21 mm breakout board'
    ],
    specs: {
      'Sensor Type': 'Semiconductor gas sensor',
      'Operating Voltage': '5 V',
      'Preheat Duration': '~20 s',
      'Analog Output': '0–5 V',
      'Digital Output': 'TTL',
      'Module Dimensions': '36 × 20 × 21 mm',
      'Detectable gases': 'Smoke, LPG, butane, hydrogen and other combustible gases',
      'Sensitivity': 'Adjustable on module'
    }
  },
  {
    id: 'sn-9',
    name: 'MPU-6050 6-Axis Accelerometer & Gyroscope Module',
    slug: 'mpu-6050-gyroscope',
    sku: 'SKU-SN-09',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256088/awie_store/sensors/mpu-6050_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256088/awie_store/sensors/mpu-6050_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256087/awie_store/sensors/mpu-6050_side-jpg.jpg'
    ],
    description: 'MPU-6050 combines a 3-axis accelerometer and 3-axis gyroscope in one motion-sensing device for orientation, movement and motion-monitoring projects.',
    features: [
      '6-axis motion tracking (3-axis Gyroscope + 3-axis Accelerometer)',
      'User-programmable gyro range: ±250 / ±500 / ±1000 / ±2000 °/s',
      'User-programmable accel range: ±2g / ±4g / ±8g / ±16g',
      'Standard I2C digital interface for robotics, drones, and orientation tracking'
    ],
    specs: {
      'Sensor': '3-axis accelerometer + 3-axis gyroscope',
      'Axes': '6-axis motion sensing',
      'Interface': 'I²C',
      'Accelerometer': '±2g / ±4g / ±8g / ±16g',
      'Gyroscope': '±250 / ±500 / ±1000 / ±2000 °/s',
      'Digital Interface': 'I²C',
      'Applications': 'Motion/orientation sensing'
    }
  },
  {
    id: 'sn-10',
    name: 'SW-420 Vibration Sensor Module',
    slug: 'sw-420-vibration-sensor',
    sku: 'SKU-SN-10',
    categorySlug: 'sensors',
    categoryName: 'Sensors',
    subCategory: 'Motion & Proximity',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: 'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256091/awie_store/sensors/sw-420-vibration-sensor_top-jpg.jpg',
    gallery: [
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256091/awie_store/sensors/sw-420-vibration-sensor_top-jpg.jpg',
      'https://res.cloudinary.com/hrmmi1ox/image/upload/v1788256090/awie_store/sensors/sw-420-vibration-sensor_side-jpg.jpg'
    ],
    description: 'SW-420 is a vibration detection module that detects vibration or movement and provides a digital switching output.',
    features: [
      'SW-420 normally-closed vibration sensor element',
      'LM393 comparator with adjustable sensitivity potentiometer',
      '3.3–5 V DC operating range with digital switching output (0/1)',
      'Mounting bolt holes for anti-tamper alarms and machine monitoring'
    ],
    specs: {
      'Sensor': 'SW-420 normally-closed vibration sensor',
      'Comparator': 'LM393',
      'Operating Voltage': '3.3–5 V',
      'Output': 'Digital',
      'Output Logic': '0 / 1 switching',
      'Sensitivity': 'Adjustable',
      'Mounting': 'Bolt holes',
      'Output Drive': '>15 mA'
    }
  },

  // 3. Modules (22 Items)
  {
    id: 'md-1',
    name: 'RC522 RFID Module',
    slug: 'rc522-rfid-module',
    sku: 'SKU-MD-01',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 100,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'MFRC522 IC based 13.56MHz contactless smart card communication module with SPI bus interface.',
    features: ['High integration reader IC', 'Low voltage 3.3V power', 'Supports Mifare1 S50, S70 cards'],
    specs: { 'Communication': 'SPI', 'Frequency': '13.56 MHz', 'Voltage': '3.3V' }
  },
  {
    id: 'md-2',
    name: 'TP4056 Charging Module',
    slug: 'tp4056-charging-module',
    sku: 'SKU-MD-02',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1A Lithium battery charging module with dual protection IC and Micro-USB / Type-C input.',
    features: ['1A constant current charging', 'Overcharge & over-discharge protection', 'Status indicator LEDs'],
    specs: { 'Charge Current': '1A Adjustable', 'Input Interface': 'USB Type-C' }
  },
  {
    id: 'md-3',
    name: 'TP4050 Charging Module',
    slug: 'tp4050-charging-module',
    sku: 'SKU-MD-03',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Linear Li-Ion battery charger board supporting high current thermal management.',
    features: ['Up to 1A programmable charge rate', 'Soft-start limits inrush current', 'LED status lights'],
    specs: { 'Input Voltage': '4.5V - 6V', 'Max Current': '1000mA' }
  },
  {
    id: 'md-4',
    name: '5V Relay Module',
    slug: '5v-relay-module',
    sku: 'SKU-MD-04',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Standard 5V single channel relay module with optocoupler isolation for switching AC 250V / DC 30V loads.',
    features: ['Optocoupler isolation', 'High current relay AC250V 10A', 'Status LED indicator'],
    specs: { 'Control Voltage': '5V DC', 'Max Load': 'AC 250V 10A / DC 30V 10A' }
  },
  {
    id: 'md-5',
    name: '1-Channel Relay Module',
    slug: '1-channel-relay',
    sku: 'SKU-MD-05',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Single channel isolated relay switch for high voltage appliance control.',
    features: ['NO/NC terminal blocks', 'Low level trigger support'],
    specs: { 'Trigger Current': '5mA', 'Voltage': '5V' }
  },
  {
    id: 'md-6',
    name: '2-Channel Relay Module',
    slug: '2-channel-relay',
    sku: 'SKU-MD-06',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Dual channel 5V relay board for controlling two separate electrical circuits independently.',
    features: ['Dual optocouplers', 'Independent control lines', 'Screw terminal blocks'],
    specs: { 'Channels': '2', 'Max Current': '10A per channel' }
  },
  {
    id: 'md-7',
    name: '4-Channel Relay Module',
    slug: '4-channel-relay',
    sku: 'SKU-MD-07',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 169,
    originalPrice: 169,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/relay.svg',
    description: 'Quad channel relay board equipped with optical isolation for home automation systems.',
    features: ['4 independent relays', 'Red LED channel indicators', 'Microcontroller compatible trigger'],
    specs: { 'Channels': '4', 'Rating': '10A 250VAC / 10A 30VDC' }
  },
  {
    id: 'md-8',
    name: 'L298N Motor Driver Module',
    slug: 'l298n-motor-driver-module',
    sku: 'SKU-MD-08',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 170,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-bridge motor driver module capable of driving two DC motors or one 4-wire stepper motor.',
    features: ['High power L298N IC', 'Aluminum heatsink onboard', '5V onboard regulator'],
    specs: { 'Motor Supply Voltage': '5V - 35V', 'Peak Current': '2A per bridge' }
  },
  {
    id: 'md-9',
    name: 'DRV8833 Motor Driver Module',
    slug: 'drv8833-motor-driver-module',
    sku: 'SKU-MD-09',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual MOSFET H-bridge motor driver module featuring low power loss for battery-operated mini robots.',
    features: ['Dual H-bridge driver', 'Low RDS(on) MOSFETs', 'Built-in thermal shutdown'],
    specs: { 'Operating Voltage': '2.7V - 10.8V', 'Output Current': '1.5A per channel' }
  },
  {
    id: 'md-10',
    name: 'TB6612FNG Motor Driver Module',
    slug: 'tb6612fng-motor-driver-module',
    sku: 'SKU-MD-10',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Relays & Drivers',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'High-efficiency dual DC motor driver module based on Toshiba TB6612FNG MOSFET bridge.',
    features: ['Higher efficiency than L298N', '1.2A continuous current per channel', 'Standby mode for power saving'],
    specs: { 'Supply Voltage': '15V Max', 'Continuous Current': '1.2A per channel' }
  },
  {
    id: 'md-11',
    name: 'MAX98357A I2S Audio Amplifier Module',
    slug: 'max98357a-i2s-amplifier',
    sku: 'SKU-MD-11',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Digital I2S Class-D mono audio amplifier module producing 3.2W output into a 4-ohm speaker for ESP32 sound projects.',
    features: ['Direct digital I2S input', '3.2W Class-D amplifier', 'No external MCLK required'],
    specs: { 'Output Power': '3.2W into 4Ω', 'Operating Voltage': '2.5V - 5.5V' }
  },
  {
    id: 'md-12',
    name: 'MicroSD Card Module',
    slug: 'microsd-card-module',
    sku: 'SKU-MD-12',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 59,
    originalPrice: 59,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'SPI interface MicroSD card reader board with onboard 3.3V level converter for microcontroller data logging.',
    features: ['SPI interface protocol', 'Onboard 3.3V regulator', 'Level shifting buffer IC'],
    specs: { 'Interface': 'SPI', 'Card Supported': 'Micro SD <= 2GB, Micro SDHC <= 32GB' }
  },
  {
    id: 'md-13',
    name: 'Bluetooth HC-05 Module',
    slug: 'bluetooth-hc-05-module',
    sku: 'SKU-MD-13',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Master/Slave SPP (Serial Port Protocol) Bluetooth 2.0 module for wireless serial UART communication.',
    features: ['Master & Slave mode switchable', 'Default baud rate 9600', 'Onboard button for AT commands'],
    specs: { 'Bluetooth Protocol': 'V2.0+EDR', 'Operating Voltage': '3.6V - 6V' }
  },
  {
    id: 'md-14',
    name: 'Bluetooth HC-06 Module',
    slug: 'bluetooth-hc-06-module',
    sku: 'SKU-MD-14',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Slave-only Bluetooth serial transceiver module ideal for smartphone-to-microcontroller wireless control.',
    features: ['Slave mode configuration', 'Simple UART serial interface', 'Signal status LED'],
    specs: { 'Frequency': '2.4GHz ISM', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-15',
    name: 'ESP-NOW-Compatible ESP32 Boards',
    slug: 'esp-now-compatible-esp32',
    sku: 'SKU-MD-15',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 90,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/esp32.svg',
    description: 'ESP32 development module configured for ultra-low latency connection-less ESP-NOW protocol peer-to-peer mesh.',
    features: ['Low latency peer-to-peer transmission', 'No router required', 'Configurable mesh firmware'],
    specs: { 'Protocol': 'ESP-NOW 2.4GHz', 'Range': 'Up to 200 meters line-of-sight' }
  },
  {
    id: 'md-16',
    name: 'Buzzer Module',
    slug: 'buzzer-module',
    sku: 'SKU-MD-16',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Audio & Wireless',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Active/Passive piezo buzzer driver board for audio tone generation and alert beeps.',
    features: ['S8050 transistor drive circuit', 'High sound pressure output', 'Digital pin activation'],
    specs: { 'Operating Voltage': '3.3V - 5V', 'Sound Frequency': '2.5kHz ± 300Hz' }
  },
  {
    id: 'md-17',
    name: 'RTC DS3231 Real-Time Clock Module',
    slug: 'rtc-ds3231-module',
    sku: 'SKU-MD-17',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Extremely accurate I2C real-time clock (RTC) module with integrated TCXO crystal and coin cell backup socket.',
    features: ['Integrated TCXO temperature compensated crystal', 'Battery backup coin cell holder', 'I2C interface with AT24C32 EEPROM'],
    specs: { 'Accuracy': '±2ppm', 'Interface': 'I2C' }
  },
  {
    id: 'md-18',
    name: 'Joystick Module',
    slug: 'joystick-module',
    sku: 'SKU-MD-18',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Dual-axis X/Y analog thumb joystick module with integrated push-button switch.',
    features: ['Two 10k potentiometers for X/Y axes', 'Integrated tactile click button', 'Standard 5-pin header'],
    specs: { 'Output': 'Dual Analog + Digital Push Switch', 'Voltage': '3.3V - 5V' }
  },
  {
    id: 'md-19',
    name: 'Voltage Sensor Module',
    slug: 'voltage-sensor-module',
    sku: 'SKU-MD-19',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'Resistive voltage divider module that steps down input DC voltage up to 25V for 5V ADC microcontrollers.',
    features: ['5:1 voltage divider ratio', 'Measures up to 25V DC', 'Screw terminal blocks'],
    specs: { 'Max Input Voltage': '25V DC', 'Divider Ratio': '5:1' }
  },
  {
    id: 'md-20',
    name: 'Current Sensor Module',
    slug: 'current-sensor-module',
    sku: 'SKU-MD-20',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Timing & Interfaces',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/module.svg',
    description: 'ACS712 linear Hall-effect current sensor module for measuring AC and DC electrical load current up to 20A.',
    features: ['Hall-effect current sensing', 'Galvanic isolation', 'Low noise analog signal path'],
    specs: { 'Current Range': '20A Max', 'Sensitivity': '100mV/A' }
  },
  {
    id: 'md-21',
    name: 'Step-Down Buck Converter Module',
    slug: 'step-down-buck-converter',
    sku: 'SKU-MD-21',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 DC-DC adjustable step-down buck power module converting high input voltages down to 1.25V-30V.',
    features: ['LM2596 IC switcher', 'Trimmer potentiometer adjustment', 'Up to 3A output capability'],
    specs: { 'Input Voltage': '4V - 35V', 'Output Voltage': '1.23V - 30V' }
  },
  {
    id: 'md-22',
    name: 'Step-Up Boost Converter Module',
    slug: 'boost-converter-module',
    sku: 'SKU-MD-22',
    categorySlug: 'modules',
    categoryName: 'Modules',
    subCategory: 'Charging & Power',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 2A DC-DC step-up voltage boost converter board for stepping battery voltage up to 28V.',
    features: ['High 1.2MHz switching frequency', 'Compact footprint', 'Up to 93% conversion efficiency'],
    specs: { 'Input Voltage': '2V - 24V', 'Max Output Voltage': '28V DC' }
  },

  // 4. Displays (10 Items)
  {
    id: 'dp-1',
    name: '0.96" OLED Display 128×64',
    slug: 'oled-096-128x64',
    sku: 'SKU-DP-01',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/oled-096-128x64.jpg',
    description: 'Compact monochrome OLED display with 128×64 resolution and I²C interface, ideal for showing sensor readings, status information, menus, icons and small graphical interfaces in Arduino, ESP32 and other embedded projects.',
    features: [
      'High-contrast 128×64 pixel graphic OLED display',
      'SSD1306 driver IC with I²C serial communication',
      'Self-illuminating pixels with wide viewing angle (>160°)',
      'Low power consumption (approx. 0.08W during full display)',
      'Ideal for sensor dashboards, mini consoles & wearable UIs'
    ],
    specs: {
      'Display Size': '0.96 inch',
      'Resolution': '128×64 pixels',
      'Display Type': 'OLED (Organic LED)',
      'Color': 'Monochrome',
      'Driver IC': 'SSD1306',
      'Interface': 'I²C (Address 0x3C / 0x3D)',
      'Operating Voltage': '3.3V – 5.0V DC',
      'Applications': 'Arduino, ESP32, IoT, embedded projects'
    }
  },
  {
    id: 'dp-2',
    name: '1.3" OLED Display 128×64',
    slug: 'oled-13-128x64',
    sku: 'SKU-DP-02',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/oled-13-128x64.jpg',
    description: 'Larger monochrome OLED display providing a 128×64 pixel resolution for compact embedded interfaces, menus, sensor dashboards and device status displays.',
    features: [
      'Generous 1.3" diagonal viewing area with 128×64 resolution',
      'SH1106 driver controller with Passive Matrix OLED technology',
      'Simple 4-pin I²C interface (VCC, GND, SCL, SDA)',
      'High contrast ratio for clear readability in ambient light',
      'Wide viewing angle > 160° with minimal current drain'
    ],
    specs: {
      'Display Size': '1.3 inch (approx. 34.5 × 23 mm panel)',
      'Resolution': '128×64 pixels',
      'Display Type': 'OLED',
      'Color': 'Monochrome (White/Blue)',
      'Common Driver': 'SH1106',
      'Interface': 'I²C',
      'Display Technology': 'Passive Matrix',
      'Operating Voltage': '3.3V – 5.0V',
      'Applications': 'ESP32, Arduino, IoT and embedded systems'
    }
  },
  {
    id: 'dp-3',
    name: '0.91" OLED Display 128×32',
    slug: 'oled-091-128x32',
    sku: 'SKU-DP-03',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'OLED Displays',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/oled-091-128x32.jpg',
    description: 'Ultra-compact monochrome OLED display designed for projects where space is limited. Suitable for displaying short text, sensor values, icons and device status.',
    features: [
      'Ultra-compact slim horizontal 0.91-inch form factor',
      '128×32 pixel crisp resolution',
      'I²C serial interface with standard 4-pin header',
      'Extremely low power consumption for portable battery gadgets',
      'Self-illuminating pixels requiring no backlight'
    ],
    specs: {
      'Display Size': '0.91 inch',
      'Resolution': '128×32 pixels',
      'Display Type': 'OLED',
      'Color': 'Blue / Monochrome (Variant Dependent)',
      'Driver IC': 'SSD1306',
      'Interface': 'I²C',
      'Form Factor': 'Ultra-compact slim',
      'Operating Voltage': '3.3V – 5.0V',
      'Applications': 'Wearables, IoT, Arduino and ESP32 projects'
    }
  },
  {
    id: 'dp-4',
    name: '2.4" TFT LCD Touch Display',
    slug: 'tft-24-touch',
    sku: 'SKU-DP-04',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 95,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/tft-24-touch.jpg',
    description: 'Compact color TFT touchscreen display designed for interactive Arduino, ESP32 and embedded projects. Suitable for graphical interfaces, control panels and small dashboards.',
    features: [
      '240×320 pixels 65K full-color vibrant TFT LCD',
      'Integrated touch panel for responsive interactive UI',
      'Onboard SD card socket for image and font asset storage',
      'High-speed SPI / 8-bit interface support',
      'Compatible with Adafruit GFX, TFT_eSPI, and LVGL graphics libraries'
    ],
    specs: {
      'Display Size': '2.4 inch',
      'Display Type': 'TFT LCD',
      'Touch': 'Yes (Touchscreen Panel)',
      'Typical Resolution': '240×320 pixels',
      'Color Depth': '65K RGB Colors',
      'Display Controller': 'ILI9341 / Variant Dependent',
      'Touch Interface': 'SPI / Dedicated Touch Controller (XPT2046)',
      'Operating Voltage': '3.3V – 5.0V',
      'Applications': 'Arduino, ESP32, IoT and embedded UI'
    }
  },
  {
    id: 'dp-5',
    name: '3.5" TFT LCD Touch Display',
    slug: 'tft-35-touch',
    sku: 'SKU-DP-05',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'TFT Displays',
    price: 699,
    originalPrice: 699,
    discountPercent: 0,
    inStock: true,
    stockCount: 75,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/tft-35-touch.jpg',
    description: 'Large color TFT touchscreen suitable for graphical interfaces, dashboards, control panels and embedded applications requiring a larger interactive display.',
    features: [
      'Generous 3.5" diagonal viewing area with 320×480 HD resolution',
      'Integrated touch overlay with stylus/finger touch support',
      'ILI9486 driver chip for fast screen refreshes',
      'Onboard MicroSD slot for storing bitmap UI assets',
      'Direct plug-in shield support for Arduino Mega / Uno & ESP32'
    ],
    specs: {
      'Display Size': '3.5 inch',
      'Display Type': 'TFT LCD',
      'Touch': 'Yes (Resistive / Capacitive Variant)',
      'Typical Resolution': '320×480 pixels',
      'Color': 'Full Color RGB (65K)',
      'Display Controller': 'ILI9486 / Variant Dependent',
      'Interface': 'SPI / 8-bit Parallel',
      'Operating Voltage': '3.3V – 5.0V DC',
      'Applications': 'Arduino, embedded systems, control panels and IoT'
    }
  },
  {
    id: 'dp-6',
    name: '16×2 LCD Display (Blue)',
    slug: 'lcd-16x2-blue',
    sku: 'SKU-DP-06',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD Displays',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/lcd-16x2-blue.jpg',
    description: 'Classic 16×2 character LCD with blue backlight for displaying text, numbers and basic status information. A simple and reliable choice for Arduino and microcontroller projects.',
    features: [
      '16 characters wide across 2 lines (32 total characters)',
      'High-contrast bright blue backlight with crisp white text',
      'Standard 16-pin interface compatible with HD44780 controller',
      'Support for 4-bit and 8-bit parallel microprocessor modes',
      'Built-in character generator ROM for ASCII & custom symbols'
    ],
    specs: {
      'Display Format': '16 columns × 2 rows',
      'Display Type': 'Character LCD',
      'Backlight': 'Blue LED Backlight',
      'Character Interface': 'Parallel (4-bit / 8-bit)',
      'Character Controller': 'HD44780-compatible commonly',
      'Operating Voltage': '5.0V DC',
      'Applications': 'Arduino, ESP32, automation and embedded projects'
    }
  },
  {
    id: 'dp-7',
    name: '16×2 LCD with I²C Adapter',
    slug: 'lcd-16x2-i2c',
    sku: 'SKU-DP-07',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD Displays',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/lcd-16x2-i2c.jpg',
    description: '16×2 character LCD combined with an I²C adapter, reducing the number of microcontroller pins required for displaying text and values.',
    features: [
      'Pre-soldered PCF8574 I²C backpack module',
      'Requires only 2 micro-controller I/O pins (SDA & SCL)',
      'Integrated contrast trimming potentiometer',
      'Jumper header for backlight power control',
      'Supported by standard LiquidCrystal_I2C libraries'
    ],
    specs: {
      'Display Format': '16×2 characters',
      'Display Type': 'Character LCD',
      'Backlight': 'Blue',
      'Interface': 'I²C',
      'Adapter': 'I²C backpack (PCF8574)',
      'Typical Address': '0x27 or 0x3F depending backpack',
      'Operating Voltage': '5.0V DC',
      'Applications': 'Arduino, ESP32, IoT and automation'
    }
  },
  {
    id: 'dp-8',
    name: '20×4 LCD Display with I²C',
    slug: 'lcd-20x4-i2c',
    sku: 'SKU-DP-08',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LCD Displays',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/lcd-20x4-i2c.jpg',
    description: '20×4 character LCD with an I²C interface, providing more display space than a standard 16×2 LCD. Suitable for menus, sensor dashboards and automation systems.',
    features: [
      '20 columns × 4 rows (80 total characters) for extensive telemetry',
      'Pre-mounted I²C serial backpack converter',
      'Bright blue backlight with sharp white lettering',
      'Easy 4-wire connection (VCC, GND, SDA, SCL)',
      'Onboard potentiometer for fine contrast calibration'
    ],
    specs: {
      'Display Format': '20 columns × 4 rows',
      'Display Type': 'Character LCD',
      'Backlight': 'Blue',
      'Interface': 'I²C',
      'I²C Adapter': 'Included (PCF8574 backpack)',
      'Typical Address': '0x27 or 0x3F depending module',
      'Operating Voltage': '5.0V DC',
      'Applications': 'Arduino, ESP32, IoT and automation'
    }
  },
  {
    id: 'dp-9',
    name: 'WS2812B LED Strip (30 LED/m)',
    slug: 'ws2812b-led-strip',
    sku: 'SKU-DP-09',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED & Matrix',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/ws2812b-led-strip.jpg',
    description: 'Individually addressable RGB LED strip that allows each LED to be controlled independently. Suitable for decorative lighting, status indicators, animations and IoT lighting projects.',
    features: [
      'Individually addressable 5050 RGB LEDs with built-in WS2812B IC',
      '30 LEDs per metre density for smooth animations and ambient effects',
      'Single-wire digital signal control compatible with FastLED & NeoPixel',
      'Cuttable between each individual LED for custom lengths',
      'Adhesive backing tape for easy mounting on surfaces'
    ],
    specs: {
      'LED Type': 'WS2812B',
      'LED Density': '30 LEDs/m',
      'LED Color': 'RGB Full Color',
      'Addressable': 'Individually Addressable',
      'Data Protocol': 'Single-wire digital signal (NZR)',
      'Typical Supply': '5V DC',
      'Strip Length': '1 Metre (AWIE Standard SKU)',
      'Applications': 'Arduino, ESP32, lighting effects and IoT projects'
    }
  },
  {
    id: 'dp-10',
    name: '8×8 LED Matrix with MAX7219',
    slug: 'led-matrix-8x8',
    sku: 'SKU-DP-10',
    categorySlug: 'displays',
    categoryName: 'Displays',
    subCategory: 'LED & Matrix',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/products/led-matrix-8x8.jpg',
    description: 'Compact 8×8 LED matrix module driven by the MAX7219 controller. Suitable for displaying numbers, letters, scrolling text, symbols and simple animations.',
    features: [
      '64 individually addressable bright red LED pixels',
      'Integrated MAX7219 serial input/output common-cathode display driver',
      'Cascadable daisy-chain architecture for multi-panel scrolling signs',
      '3-wire SPI digital control saving valuable microcontroller pins',
      'Low power shutdown mode with digital/analog brightness control'
    ],
    specs: {
      'Matrix Size': '8×8 (64 LEDs)',
      'Total LEDs': '64',
      'Driver IC': 'MAX7219',
      'Interface': 'Serial / SPI-style (DIN, CS, CLK)',
      'Control': 'Digital 3-Wire',
      'Daisy-chain Capable': 'Yes (Cascadable)',
      'Operating Voltage': '5.0V DC',
      'Applications': 'Arduino, ESP32, clocks, counters and scrolling displays'
    }
  },

  // 5. Motors & Drivers (17 Items)
  {
    id: 'mt-1',
    name: 'SG90 Servo Motor',
    slug: 'sg90-servo-motor',
    sku: 'SKU-MT-01',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 89,
    originalPrice: 89,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: '9g lightweight micro servo motor with 180-degree rotation, plastic gears, and mounting horns.',
    features: ['180 degree rotation angle', '1.8 kg/cm holding torque', 'Includes 3 servo horns'],
    specs: { 'Torque': '1.8 kg-cm @ 4.8V', 'Weight': '9 grams', 'Speed': '0.12 sec/60 deg' }
  },
  {
    id: 'mt-2',
    name: 'MG90S Servo Motor',
    slug: 'mg90s-servo-motor',
    sku: 'SKU-MT-02',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'Micro metal gear 9g servo motor offering increased durability and torque for robotic arms.',
    features: ['Full metal gear train', '2.2 kg/cm torque at 6V', 'Dual ball bearing'],
    specs: { 'Gears': 'Metal', 'Torque': '2.2 kg-cm' }
  },
  {
    id: 'mt-3',
    name: 'MG996R Servo Motor',
    slug: 'mg996r-servo-motor',
    sku: 'SKU-MT-03',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Servo Motors',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 150,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/servo.svg',
    description: 'High-torque standard size digital metal gear servo motor providing up to 11 kg/cm torque.',
    features: ['Metal internal gears', 'Heavy-duty 11 kg/cm torque', 'Double ball bearing shaft'],
    specs: { 'Torque': '11 kg-cm @ 6V', 'Rotation': '180 Degrees' }
  },
  {
    id: 'mt-4',
    name: '8520 Coreless Motor',
    slug: '8520-coreless-motor',
    sku: 'SKU-MT-04',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Ultra-fast 8.5x20mm micro coreless DC motor designed for micro quadcopters and lightweight RC models.',
    features: ['High speed 45,000 RPM @ 3.7V', 'Lightweight coreless design', 'Pre-wired leads'],
    specs: { 'Size': '8.5mm x 20mm', 'Voltage': '3.7V DC', 'Speed': '45000 RPM' }
  },
  {
    id: 'mt-5',
    name: 'TT Gear Motor',
    slug: 'tt-gear-motor',
    sku: 'SKU-MT-05',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual-axis plastic gearbox DC motor for smart robot car chassis with 1:48 gear ratio.',
    features: ['1:48 reduction gear ratio', 'EMC anti-interference magnetic core', 'Dual output shaft'],
    specs: { 'Voltage': '3V - 6V DC', 'Ratio': '1:48' }
  },
  {
    id: 'mt-6',
    name: 'N20 Gear Motor',
    slug: 'n20-gear-motor',
    sku: 'SKU-MT-06',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Miniature precision metal gearbox DC motor providing high torque in a compact 12mm profile.',
    features: ['All-metal micro spur gearbox', 'D-shaped output shaft', 'Operating voltage 3V-12V'],
    specs: { 'Speed': '100 RPM / 300 RPM', 'Voltage': '6V DC' }
  },
  {
    id: 'mt-7',
    name: 'DC Motor',
    slug: 'dc-toy-motor',
    sku: 'SKU-MT-07',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'DC Motors',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Standard 130-size hobby DC motor running from 3V to 6V for school projects and fan propellers.',
    features: ['130 form factor', 'High RPM rotation', 'Universal hobby motor'],
    specs: { 'Voltage': '3V - 6V DC', 'RPM': '9000 RPM' }
  },
  {
    id: 'mt-8',
    name: 'Stepper Motor 28BYJ-48',
    slug: 'stepper-motor-28byj-48',
    sku: 'SKU-MT-08',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: '5V 4-phase geared 28BYJ-48 stepper motor bundled with ULN2003 driver board.',
    features: ['5V DC 4-phase stepper motor', 'Includes ULN2003 driver PCB', '1/64 gear reduction ratio'],
    specs: { 'Step Angle': '5.625 x 1/64', 'Voltage': '5V DC' }
  },
  {
    id: 'mt-9',
    name: 'NEMA 17 Stepper Motor',
    slug: 'nema-17-stepper-motor',
    sku: 'SKU-MT-09',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Stepper Motors',
    price: 549,
    originalPrice: 549,
    discountPercent: 0,
    inStock: true,
    stockCount: 110,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'High torque 1.8-degree bipolar NEMA 17 stepper motor for 3D printers and CNC routers.',
    features: ['4.2 kg-cm holding torque', '1.8 degree step angle', '4-wire bipolar connection'],
    specs: { 'Step Angle': '1.8°', 'Holding Torque': '42 N.cm', 'Rated Current': '1.5A' }
  },
  {
    id: 'mt-10',
    name: 'L298N Motor Driver',
    slug: 'l298n-motor-driver',
    sku: 'SKU-MT-10',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Dual H-Bridge power driver module suitable for driving heavy DC gear motors and steppers.',
    features: ['Up to 2A per channel', 'Integrated 5V regulator logic supply', 'Robust terminal blocks'],
    specs: { 'Max Voltage': '35V', 'Peak Current': '2A' }
  },
  {
    id: 'mt-11',
    name: 'L293D Motor Driver',
    slug: 'l293d-motor-driver-shield',
    sku: 'SKU-MT-11',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 119,
    originalPrice: 119,
    discountPercent: 0,
    inStock: true,
    stockCount: 160,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Arduino Uno motor driver shield capable of driving 4 DC motors or 2 stepper motors simultaneously.',
    features: ['4 H-bridges L293D chipset', '0.6A per bridge', 'Dedicated 2-pin terminal block for external power'],
    specs: { 'Drive Capacity': '4 DC Motors or 2 Steppers', 'Voltage': '4.5V - 25V' }
  },
  {
    id: 'mt-12',
    name: 'DRV8833 Motor Driver',
    slug: 'drv8833-motor-driver',
    sku: 'SKU-MT-12',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 99,
    originalPrice: 99,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Low-voltage dual H-bridge motor driver breakout module with current limiting.',
    features: ['1.5A per channel', 'Over-current protection', 'Low standby current'],
    specs: { 'Voltage': '2.7V - 10.8V', 'Current': '1.5A' }
  },
  {
    id: 'mt-13',
    name: 'TB6612FNG Motor Driver',
    slug: 'tb6612fng-motor-driver',
    sku: 'SKU-MT-13',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 129,
    originalPrice: 129,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Toshiba dual channel MOSFET motor driver offering low heat dissipation.',
    features: ['1.2A continuous current', 'PWM frequency up to 100kHz', 'Decoupling capacitors included'],
    specs: { 'Operating Current': '1.2A', 'Max Peak': '3.2A' }
  },
  {
    id: 'mt-14',
    name: 'A4988 Stepper Driver',
    slug: 'a4988-stepper-driver',
    sku: 'SKU-MT-14',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/stepper.svg',
    description: 'Microstepping bipolar stepper motor driver module with translator and aluminum heatsink for 3D printers.',
    features: ['Five step resolutions down to 1/16 microstepping', 'Adjustable current control', 'Thermal shutdown'],
    specs: { 'Max Current': '2A with heatsink', 'Microstep Resolutions': 'Full, 1/2, 1/4, 1/8, 1/16' }
  },
  {
    id: 'mt-15',
    name: 'Motor Wheels',
    slug: 'motor-wheels',
    sku: 'SKU-MT-15',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: '65mm diameter rubber tire with D-hole center hub designed for TT gear motors.',
    features: ['High traction rubber tread', '65mm diameter', 'Center D-shaft coupler'],
    specs: { 'Diameter': '65mm', 'Width': '27mm' }
  },
  {
    id: 'mt-16',
    name: 'Robot Chassis',
    slug: 'robot-chassis-kit',
    sku: 'SKU-MT-16',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 249,
    originalPrice: 249,
    discountPercent: 0,
    inStock: true,
    stockCount: 130,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Transparent acrylic 2WD smart robot car chassis platform with TT motors, wheels, and caster wheel.',
    features: ['Laser cut acrylic frame', 'Includes 2 TT motors & 65mm wheels', 'Omnidirectional caster wheel'],
    specs: { 'Platform': '2WD', 'Material': 'Acrylic' }
  },
  {
    id: 'mt-17',
    name: 'Motor Couplings',
    slug: 'motor-couplings',
    sku: 'SKU-MT-17',
    categorySlug: 'motors-drivers',
    categoryName: 'Motors & Drivers',
    subCategory: 'Motor Drivers & Chassis',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/motor.svg',
    description: 'Solid brass motor shaft coupling connector for linking N20 / DC motor shafts to wheels.',
    features: ['Solid brass alloy', 'Includes grub screws and hex wrench key', 'Precise shaft fit'],
    specs: { 'Shaft Bore': '3mm / 4mm / 5mm' }
  },

  // 6. Power & Battery (22 Items)
  {
    id: 'pb-1',
    name: '18650 Li-Ion Battery',
    slug: '18650-li-ion-battery',
    sku: 'SKU-PB-01',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 149,
    originalPrice: 149,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Standard 3.7V rechargeable 18650 cylindrical lithium-ion cell with 2200mAh capacity for power banks and electronics.',
    features: ['High energy density', '3.7V nominal voltage', 'Rechargeable up to 500 cycles'],
    specs: { 'Capacity': '2200mAh', 'Nominal Voltage': '3.7V', 'Full Charge Voltage': '4.2V' }
  },
  {
    id: 'pb-2',
    name: '3.7V Li-Po Battery',
    slug: '3-7v-lipo-battery',
    sku: 'SKU-PB-02',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 199,
    originalPrice: 199,
    discountPercent: 0,
    inStock: true,
    stockCount: 250,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Ultra-thin lithium polymer pouch battery cell for embedded wearables and compact microcontrollers.',
    features: ['Flat pouch form factor', 'Integrated PCM protection board', 'JST-PH connector'],
    specs: { 'Voltage': '3.7V', 'Capacity': '500mAh' }
  },
  {
    id: 'pb-3',
    name: '3.7V 750mAh Li-Po',
    slug: '3-7v-750mah-lipo',
    sku: 'SKU-PB-03',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 179,
    originalPrice: 179,
    discountPercent: 0,
    inStock: true,
    stockCount: 200,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: '3.7V 750mAh high-discharge Li-Po battery pack fitted with protection circuit module.',
    features: ['750mAh power capacity', 'Over-current protection', 'JST connector lead'],
    specs: { 'Capacity': '750mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-4',
    name: '3.7V 1200mAh Li-Po',
    slug: '3-7v-1200mah-lipo',
    sku: 'SKU-PB-04',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 229,
    originalPrice: 229,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Rechargeable 3.7V 1200mAh lithium polymer battery suitable for portable companion devices like GEM.',
    features: ['Long operating runtime', 'High reliability pouch cell', 'Pre-soldered JST leads'],
    specs: { 'Capacity': '1200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-5',
    name: '3.7V 2200mAh Li-Po',
    slug: '3-7v-2200mah-lipo',
    sku: 'SKU-PB-05',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Li-Ion & Li-Po',
    price: 349,
    originalPrice: 349,
    discountPercent: 0,
    inStock: true,
    stockCount: 140,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'High capacity 2200mAh 3.7V Li-Po battery pack providing extended power autonomy.',
    features: ['2200mAh heavy duty capacity', 'Integrated short-circuit protection'],
    specs: { 'Capacity': '2200mAh', 'Voltage': '3.7V' }
  },
  {
    id: 'pb-6',
    name: '5V USB Power Module',
    slug: '5v-usb-power-module',
    sku: 'SKU-PB-06',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Dual USB 5V 2A power bank motherboard module with charging status digital LED indicators.',
    features: ['Dual 5V 2.1A USB outputs', 'Type-C / Micro-USB input charging', 'Overload & thermal protection'],
    specs: { 'Output': '5V 2.1A', 'Input': '5V 1A' }
  },
  {
    id: 'pb-7',
    name: 'TP4056 Charger Module',
    slug: 'tp4056-charger-module',
    sku: 'SKU-PB-07',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 450,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'Single-cell 1A lithium battery charging module with Type-C connector and protection IC.',
    features: ['1A charging current', 'Type-C port input', 'Red/Blue status LEDs'],
    specs: { 'Charge Current': '1A', 'Port': 'USB Type-C' }
  },
  {
    id: 'pb-8',
    name: 'TP4050 Charger Module',
    slug: 'tp4050-charger-module',
    sku: 'SKU-PB-08',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 45,
    originalPrice: 45,
    discountPercent: 0,
    inStock: true,
    stockCount: 280,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: 'High efficiency linear Li-Ion charger board with thermal foldback protection.',
    features: ['Thermal regulation', 'Programmable charging current', 'Compact PCB footprint'],
    specs: { 'Voltage': '4.5V - 6.5V', 'Current': '1000mA' }
  },
  {
    id: 'pb-9',
    name: '1S BMS Protection Board',
    slug: '1s-bms-protection-board',
    sku: 'SKU-PB-09',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 29,
    originalPrice: 29,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '1S 3.7V 3A lithium battery Battery Management System (BMS) protection PCB.',
    features: ['Overcharge cut-off 4.25V', 'Over-discharge cut-off 2.54V', 'Short circuit protection'],
    specs: { 'Series': '1S (3.7V)', 'Max Current': '3A' }
  },
  {
    id: 'pb-10',
    name: '2S BMS Protection Board',
    slug: '2s-bms-protection-board',
    sku: 'SKU-PB-10',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 49,
    originalPrice: 49,
    discountPercent: 0,
    inStock: true,
    stockCount: 220,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '2S 7.4V 8A BMS protection board for dual 18650 Li-Ion battery pack balancing.',
    features: ['Cell voltage balancing', '8A continuous discharge limit', 'Low heat MOSFETs'],
    specs: { 'Series': '2S (7.4V / 8.4V)', 'Max Current': '8A' }
  },
  {
    id: 'pb-11',
    name: '3S BMS Protection Board',
    slug: '3s-bms-protection-board',
    sku: 'SKU-PB-11',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'BMS & Chargers',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 190,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/bms.svg',
    description: '3S 12V 20A Li-Ion battery BMS protection PCB board for power tools and 12V packs.',
    features: ['20A peak load discharge', 'Overcharge, overdischarge & short circuit cutoffs'],
    specs: { 'Series': '3S (11.1V / 12.6V)', 'Current': '20A' }
  },
  {
    id: 'pb-12',
    name: 'Battery Holder 1×18650',
    slug: 'battery-holder-1x18650',
    sku: 'SKU-PB-12',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Single-slot 18650 battery holder case with wire leads for easy breadboard connection.',
    features: ['High quality ABS plastic', 'Pre-stripped red/black wire leads', 'Metal leaf spring contacts'],
    specs: { 'Slots': '1 x 18650 Cell' }
  },
  {
    id: 'pb-13',
    name: 'Battery Holder 2×18650',
    slug: 'battery-holder-2x18650',
    sku: 'SKU-PB-13',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 35,
    originalPrice: 35,
    discountPercent: 0,
    inStock: true,
    stockCount: 300,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Dual-slot 2x18650 battery holder socket case wired in series for 7.4V power supply.',
    features: ['Holds two 18650 cells', 'Series output wiring', 'M3 mounting holes'],
    specs: { 'Slots': '2 x 18650 Cells' }
  },
  {
    id: 'pb-14',
    name: 'Battery Holder 4×18650',
    slug: 'battery-holder-4x18650',
    sku: 'SKU-PB-14',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 55,
    originalPrice: 55,
    discountPercent: 0,
    inStock: true,
    stockCount: 180,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/battery.svg',
    description: 'Quad-slot 4x18650 battery holder enclosure case for heavy duty 14.8V power packs.',
    features: ['4 slot 18650 enclosure', 'Robust spring contacts', 'Wire leads included'],
    specs: { 'Slots': '4 x 18650 Cells' }
  },
  {
    id: 'pb-15',
    name: 'DC-DC Buck Converter',
    slug: 'dc-dc-buck-converter',
    sku: 'SKU-PB-15',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 69,
    originalPrice: 69,
    discountPercent: 0,
    inStock: true,
    stockCount: 260,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM2596 adjustable DC-DC step down voltage regulator module providing stable output voltage.',
    features: ['Input up to 35V DC', 'Output adjustable 1.25V-30V', 'High conversion efficiency'],
    specs: { 'Max Current': '3A', 'Efficiency': '92%' }
  },
  {
    id: 'pb-16',
    name: 'DC-DC Boost Converter',
    slug: 'dc-dc-boost-converter',
    sku: 'SKU-PB-16',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 79,
    originalPrice: 79,
    discountPercent: 0,
    inStock: true,
    stockCount: 240,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'MT3608 micro 2A DC-DC step up voltage booster board.',
    features: ['Steps 2V up to 28V', 'Compact 36mm x 17mm size', 'Trimmer pot adjustment'],
    specs: { 'Max Current': '2A' }
  },
  {
    id: 'pb-17',
    name: '5V Voltage Regulator',
    slug: '5v-voltage-regulator',
    sku: 'SKU-PB-17',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'LM7805 TO-220 3-terminal positive 5V 1.5A fixed linear voltage regulator IC.',
    features: ['Fixed 5V output', 'Thermal overload protection', 'Short-circuit current limit'],
    specs: { 'Output Voltage': '5V DC', 'Max Current': '1.5A' }
  },
  {
    id: 'pb-18',
    name: '3.3V Voltage Regulator',
    slug: '3-3v-voltage-regulator',
    sku: 'SKU-PB-18',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Voltage Regulators & Holders',
    price: 25,
    originalPrice: 25,
    discountPercent: 0,
    inStock: true,
    stockCount: 400,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'AMS1117-3.3 SOT-223 low dropout (LDO) 3.3V 800mA linear regulator IC module.',
    features: ['Fixed 3.3V LDO output', '800mA output current capability', 'Onboard filter capacitors'],
    specs: { 'Output Voltage': '3.3V DC', 'Max Output Current': '800mA' }
  },
  {
    id: 'pb-19',
    name: 'USB Type-C Power Module',
    slug: 'usb-type-c-power-module',
    sku: 'SKU-PB-19',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 39,
    originalPrice: 39,
    discountPercent: 0,
    inStock: true,
    stockCount: 350,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'USB Type-C female connector breakout board with DIP pins for 5V power input connection.',
    features: ['Standard Type-C receptacle', 'VBUS, GND, CC1, CC2 breakout pins', 'FR-4 PCB'],
    specs: { 'Interface': 'USB Type-C Female' }
  },
  {
    id: 'pb-[#0066FF]',
    name: 'Rocker / Slide Power Switch',
    slug: 'rocker-slide-power-switch',
    sku: 'SKU-PB-20',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 600,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'SPST 2-pin mini ON/OFF power toggle switch for electronic projects.',
    features: ['Snap-in mounting', 'AC 250V 3A / DC 12V 6A rating', 'Tactile latching click'],
    specs: { 'Switch Type': 'SPST ON-OFF' }
  },
  {
    id: 'pb-21',
    name: 'JST Connectors',
    slug: 'jst-connectors-pair',
    sku: 'SKU-PB-21',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 20,
    originalPrice: 20,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'JST-PH 2.0mm 2-pin male and female connector cable pair with 10cm pre-stripped wires.',
    features: ['2.0mm pitch spacing', 'Includes male plug & female socket cable', '22AWG copper wire'],
    specs: { 'Pitch': '2.0mm JST-PH', 'Length': '10cm' }
  },
  {
    id: 'pb-22',
    name: 'DC Barrel Jack',
    slug: 'dc-barrel-jack-socket',
    sku: 'SKU-PB-22',
    categorySlug: 'power-battery',
    categoryName: 'Power & Battery',
    subCategory: 'Connectors & Switches',
    price: 15,
    originalPrice: 15,
    discountPercent: 0,
    inStock: true,
    stockCount: 500,
    rating: 5.0,
    reviewCount: 0,
    image: '/store/power.svg',
    description: 'Standard 5.5mm x 2.1mm DC power female jack socket connector for wall adapter plugs.',
    features: ['5.5x2.1mm standard DC dimensions', 'Panel mount / PCB mount pins', 'Durable metal contacts'],
    specs: { 'Dimensions': '5.5mm x 2.1mm' }
  }
];